NRFU test case placeholders
aristanetworks/vane pull request #469
Opened 2023-08-25 15:05 UTC by vishwajeetgslab

# Please include a summary of the changes

* nrfu_tests/master_def.yaml: Added placeholder for testcases. Which will keep the testcases in sequence in file also it will avoid the conflicts on another PR when one of the PR is merged.
* nrfu_tests/test_definition.yaml: Added placeholder for testcases. Which will keep the testcases in sequence in file also it will avoid the conflicts on another PR when one of the PR is merged.
* nrfu_tests/test_definition.yaml.j2: Added placeholder for testcases. Which will keep the testcases in sequence in file also it will avoid the conflicts on another PR when one of the PR is merged.

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link

Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (Testcase placeholder)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-25 16:30 UTC, MaheshGSLAB approved these changes

2023-08-28 13:13 UTC, kgrozis-arista requested changes

2023-08-28 13:13 UTC, kgrozis-arista commented on nrfu_tests/master_def.yaml
> +  report_style: modern # If report type is set to modern, then it will update steps, assumptions, and external systems in the docx report.
report_style isn't needed in master def.  it should always be set to modern

2023-08-28 13:13 UTC, kgrozis-arista commented on nrfu_tests/master_def.yaml
> +common_data:
dut filter global parameter.  if it is not set nrfu test cases should default  to all duts.

2023-08-28 13:13 UTC, kgrozis-arista commented on nrfu_tests/master_def.yaml
> +testcase_data:
Most test cases will not have any parameters. We want to make nrfu testing very simple.  If there isn't a parameter we shouldn't have a placeholder.  Example if no parameters for NRFU1.1, we should not have mentions to the test case:
NRFU1.1: None
NRFU1.1: {}

2023-08-28 13:13 UTC, kgrozis-arista commented on nrfu_tests/test_definition.yaml.j2
> +      report_style: {{ report_style }}
Hard code this to modern

2023-08-28 13:13 UTC, kgrozis-arista commented on nrfu_tests/test_definition.yaml.j2
> +      criteria: {{ test_data["criteria"] }}
Set this value using global dut filter setting

2023-08-28 16:02 UTC, vishwajeetgslab commented on nrfu_tests/master_def.yaml
> +  report_style: modern # If report type is set to modern, then it will update steps, assumptions, and external systems in the docx report.
Removed report_style parameter from master definitions. Added modern as in j2 file.

2023-08-28 16:03 UTC, vishwajeetgslab commented on nrfu_tests/master_def.yaml
> +common_data:
Add global_dut_filter as a parameter in master def.

2023-08-28 16:03 UTC, vishwajeetgslab commented on nrfu_tests/master_def.yaml
> +testcase_data:
Updated as suggested.

2023-08-28 16:04 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml.j2
> +      report_style: {{ report_style }}
Added modern directly in j2 file now. Thanks

2023-08-28 16:04 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml.j2
> +      criteria: {{ test_data["criteria"] }}
Updated. Thanks

2023-08-29 18:48 UTC, kgrozis-arista commented on nrfu_tests/master_def.yaml
> +global_dut_filter:
This stanza is optional.  If it is not provided by users than all test cases should be run on each dut.

2023-08-30 05:58 UTC, geetanjalimanegslab approved these changes

2023-08-30 14:54 UTC, kgrozis-arista requested changes

2023-08-30 14:54 UTC, kgrozis-arista commented on nrfu_tests/test_definition.yaml.j2
> +      criteria: {{ global_dut_filter.criteria }}
If no DUT filter is set then this will break because it will call variables that do not exist

2023-09-05 15:30 UTC, shachiagarwal approved these changes

2023-09-05 18:42 UTC, kgrozis-arista approved these changes

2023-09-05 18:43 UTC, merged