Issue-453 Convert Pytest-CVP Enable Password test case to Vane
aristanetworks/vane pull request #475
Opened 2023-08-28 09:14 UTC by Dakshatagslab

# Please include a summary of the changes

* master_def.yaml
  Updated master def for testcase NRFU5.2
* test_definition.yaml.j2
  Updated j2 file for testcase NRFU5.2
* test_definition.yaml
  Updated test def for testcase NRFU5.2
* test_password_enable_functionality.py
  Added python file for testcase NRFU5.2

# Any specific logic/part of code you need extra attention on

This testcase will check if output starts with 'enable password' then testcase will pass 
and if output is not found then testcase will fail with output message.

# Include the Issue number and link

https://github.com/aristanetworks/vane/issues/453

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (Convert PyTest-CVP Enable Password test case)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?

If output starts with 'enable password ' then testcase will pass(Tested with hardcoded output)

**Reports:**
 
[Pass_reports.zip](https://github.com/aristanetworks/vane/files/12452782/Pass_reports.zip)

If output found as empty then testcase will fail

**Reports:**
[report_fail.zip](https://github.com/aristanetworks/vane/files/12452789/report_fail.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-29 05:56 UTC, AbhijeetGSLAB commented on nrfu_tests/test_password_enable_functionality.py
> +@pytest.mark.nrfu_tests
Update the marker to `nrfu_test`

2023-08-29 06:05 UTC, AbhijeetGSLAB commented on nrfu_tests/test_password_enable_functionality.py
> +        TD: Testcase for verification of NRFU5.2 enable password is configured.
Remove the test id from TD here

2023-08-29 06:07 UTC, AbhijeetGSLAB commented on nrfu_tests/test_password_enable_functionality.py
> +            hostname = tops.run_show_cmds([show_cmd])[0]["result"]["hostname"]
I think this is not needed using pyeapi. We can directly access the hostname using tops.dut_name. Please confirm the same with Vishwajeet or Mahesh and do the necessary changes in the testcase file

2023-08-29 06:08 UTC, AbhijeetGSLAB commented on nrfu_tests/test_password_enable_functionality.py
> +                if not enable_password_found:
We will need to check the condition on actual output

2023-08-29 06:15 UTC, AbhijeetGSLAB commented on nrfu_tests/test_password_enable_functionality.py
> +"""Testcase for verification of enable password is configured."""
Please follow the file naming as per the files present in pytest-cvp issue.

In this case it will be `test_security_rp_enable_pw.py`

2023-08-30 08:44 UTC, AbhijeetGSLAB approved these changes

2023-08-31 05:20 UTC, geetanjalimanegslab commented on nrfu_tests/test_security_rp_enable_pw.py
> +            output = tops.run_show_cmds([tops.show_cmd])[0]["result"]["output"]
please add output = tops.run_show_cmds([tops.show_cmd]) output in the logger and self.output creates new variable and store the running_conf_output = tops.run_show_cmds([tops.show_cmd])[0]["result"]["output"]

2023-08-31 05:20 UTC, geetanjalimanegslab commented on nrfu_tests/test_security_rp_enable_pw.py
> +            if output.startswith("enable password "):
```suggestion
            if output.startswith("enable password"):
```

2023-08-31 05:20 UTC, geetanjalimanegslab commented on nrfu_tests/test_security_rp_enable_pw.py
> +        enable_password_found = False
```suggestion
        tops.actual_output = {"enable_password_found": False}
```

2023-08-31 05:20 UTC, geetanjalimanegslab commented on nrfu_tests/test_security_rp_enable_pw.py
> +        tops.actual_output = {}
remove this line

2023-08-31 05:20 UTC, geetanjalimanegslab commented on nrfu_tests/test_security_rp_enable_pw.py
> +            tops.actual_output = {"enable_password_found": enable_password_found}
remove this line

2023-08-31 05:20 UTC, geetanjalimanegslab commented on nrfu_tests/test_security_rp_enable_pw.py
> +                enable_password_found = True
```suggestion
                tops.actual_output = {"enable_password_found": True}
```

2023-08-31 05:20 UTC, geetanjalimanegslab commented on nrfu_tests/test_security_rp_enable_pw.py
> +                if tops.expected_output.get("enable_password_found") != tops.actual_output.get(
```suggestion
                if not tops.actual_output["enable_password_found"]:
```

2023-08-31 12:55 UTC, geetanjalimanegslab requested changes

2023-08-31 12:55 UTC, geetanjalimanegslab commented on nrfu_tests/test_security_rp_enable_pw.py
> +        except (AssertionError, AttributeError, LookupError, EapiError) as excep:
remove the Assertion error if it is not required.

2023-09-01 05:48 UTC, MaheshGSLAB commented
Configure device with enable password so you can get the evidence for the same in output
![image](https://github.com/aristanetworks/vane/assets/122076792/301f234e-18aa-40b8-a46c-c49f46374ff9)

2023-09-01 05:50 UTC, MaheshGSLAB requested changes

2023-09-01 05:50 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_enable_pw.py
> +class SecurityEnablePasswordTests:
```suggestion
class EnablePasswordTests:
```

2023-09-01 05:50 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_enable_pw.py
> +            TS: Running `show running-config section enable` command and verifying password is
```suggestion
            TS: Running `show running-config section enable` command and verifying enable prompt password is
```

2023-09-01 05:50 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_enable_pw.py
> +            output = tops.run_show_cmds([tops.show_cmd])
why you are using wrapper function when command is already defined in test def

2023-09-01 05:50 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_enable_pw.py
> +                if not tops.actual_output.get("enable_password_found"):
there is only single key and value so no need to add second if condition.

2023-09-01 05:50 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +      enable_password_found: true
```suggestion
      enable_password_configured: true
```

2023-09-04 10:08 UTC, geetanjalimanegslab approved these changes

2023-09-13 13:05 UTC, kgrozis-arista approved these changes

2023-09-14 13:32 UTC, MaheshGSLAB approved these changes

2023-09-26 16:38 UTC, merged