issue-448: Automated test case for Convert Pytest-CVP Power Supply Status case to Vane
aristanetworks/vane pull request #476
Opened 2023-08-28 10:09 UTC by vishwajeetgslab

# Please include a summary of the changes

test_definition.yaml: Updated test def with testcase NRFU6.9.
test_definition.yaml.j2: Updated J2 with testcase NRFU6.9.
master_def.yaml: Updated master def with testcase NRFU6.9.
test_security_rp_ssh_access_list.py: Added python file for testcase NRFU6.9.

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on
This testcase will verify the power voltage sensor status in  `show system environment power voltage` command output if power supply sensors are not found test case will fail with assertion error. If device platform is vEOS the test case will skip.

# Include the Issue number and link
#448 
Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [X] Other (NRFU testcases)

# Effort required on reviewers end

- - [X] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?
Unit test cases:
1. If power supply  voltage sensor are Ok - test case should pass  - Passed. 
[report_2308281502.docx](https://github.com/aristanetworks/vane/files/12453240/report_2308281502.docx)
[report.zip](https://github.com/aristanetworks/vane/files/12453242/report.zip)

2. If device platform is vEOS test case should be skipped. - Skipped (Docx report doesn't contain output)
[report_2308281503.docx](https://github.com/aristanetworks/vane/files/12453238/report_2308281503.docx)
[report.zip](https://github.com/aristanetworks/vane/files/12453247/report.zip)

3. If power supply voltage sensors are not found in output - test case should fail - Failed.
[report_2308281456.docx](https://github.com/aristanetworks/vane/files/12453233/report_2308281456.docx)
[report.zip](https://github.com/aristanetworks/vane/files/12453251/report.zip)

4. If Power supply voltage status is not 'ok' - test case should fail- failed.
[report_2308281454.docx](https://github.com/aristanetworks/vane/files/12453219/report_2308281454.docx)
[report.zip](https://github.com/aristanetworks/vane/files/12453254/report.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-30 04:59 UTC, MaheshGSLAB requested changes

2023-08-30 04:59 UTC, MaheshGSLAB commented on nrfu_tests/master_def.yaml
> +  NRFU6.10: {}
update you master def and J2 as per Kevin suggestion

2023-08-30 04:59 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +      show_cmd: show version
Vane runs this show version command so can you check if we can use the output from there

2023-08-30 04:59 UTC, MaheshGSLAB commented on nrfu_tests/test_hardware_power_supply_voltage_status.py
> +# Copyright (c) 2022 Arista Networks, Inc.  All rights reserved.
```suggestion
# Copyright (c) 2023 Arista Networks, Inc.  All rights reserved.
```

2023-08-30 04:59 UTC, MaheshGSLAB commented on nrfu_tests/test_hardware_power_supply_voltage_status.py
> +class SystemHardwarePowerSupplyVoltageTests:
```suggestion
class PowerSupplyVoltageTests:
```

2023-08-30 04:59 UTC, MaheshGSLAB commented on nrfu_tests/test_hardware_power_supply_voltage_status.py
> +            voltage_sensors = voltage_cmd_output[0]["result"]["voltageSensors"]
please use get method for "voltageSensors"

2023-08-30 10:17 UTC, MaheshGSLAB approved these changes

2023-08-30 12:18 UTC, geetanjalimanegslab commented on nrfu_tests/test_hardware_power_supply_voltage_status.py
> +            TS: Running 'show version' command on device and Skipping the test case
```suggestion
            TS: Running 'show version' command on device and skipping the test case
```

2023-08-31 07:07 UTC, geetanjalimanegslab approved these changes

2023-09-13 13:32 UTC, kgrozis-arista approved these changes

2023-09-28 20:46 UTC, merged