issue_420: Converted Pytest-CVP NTP test case to Vane #420
aristanetworks/vane pull request #477
Opened 2023-08-28 11:19 UTC by geetanjalimanegslab

# Please include a summary of the changes
Converted test_base_services_ntp_association.py as per the vane style guide along with that updated following files.
test_definition.yaml: Updated test def with testcase NRFU1.2
test_definition.yaml.j2: Updated J2 with testcase NRFU1.2.
nrfu_tests/test_base_services_ntp_association.py: Added testcase for NRFU1.2.

# Any specific logic/part of code you need extra attention on
Verified primary and secondary associations using the output of `show ntp associations` command, if NTP server is not configured testcase will skip.

# Include the Issue number and link
https://github.com/aristanetworks/vane/issues/420

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU testcases)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?
   Unit tests
   - Tested the NTP server is configured and primary and secondary association is present.
       Reports:
       [report_ntp_pass.docx](https://github.com/aristanetworks/vane/files/12608197/report_ntp_pass.docx)

   - Tested for NTP server is not configured
      Reports:
     [report_ntp_not_configured.docx](https://github.com/aristanetworks/vane/files/12488676/report_ntp_not_configured.docx)

 -  Tested for NTP association details are not found**(Tested with hardcoded output)**
    Reports:
    [report_ntp_association_empty.docx](https://github.com/aristanetworks/vane/files/12488679/report_ntp_association_empty.docx)

- Tested for NTP  primary and secondary association details are not present. **(Tested with hardcoded output)**
    Reports:
    [report_both_ntp_association_not_found.docx](https://github.com/aristanetworks/vane/files/12488685/report_both_ntp_association_not_found.docx)

- Tested for NTP secondary association details are not present **(Tested with hardcoded output)**
  Reports:
  [report_sec_NTP_association_not_found.docx](https://github.com/aristanetworks/vane/files/12488687/report_sec_NTP_association_not_found.docx)

   
HTML reports for all mentioned unit testcases
[ntp.zip](https://github.com/aristanetworks/vane/files/12608198/ntp.zip)

   

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-29 08:48 UTC, MaheshGSLAB requested changes

2023-08-29 08:48 UTC, MaheshGSLAB commented on nrfu_tests/master_def.yaml
> +common_data:
Update the master def and J2 as suggested by Kevin

2023-08-29 08:48 UTC, MaheshGSLAB commented on nrfu_tests/test_base_services_ntp_association.py
> +# Copyright (c) 2022 Arista Networks, Inc.  All rights reserved.
```suggestion
# Copyright (c) 2023 Arista Networks, Inc.  All rights reserved.
```

2023-08-29 08:48 UTC, MaheshGSLAB commented on nrfu_tests/test_base_services_ntp_association.py
> +        tops.actual_output = {"primary_ntp_association": False, "secondary_ntp_association": False}
```suggestion
        tops.actual_output = {"primary_ntp_association": Not found, "secondary_ntp_association": Not found}
```

2023-08-29 08:48 UTC, MaheshGSLAB commented on nrfu_tests/test_base_services_ntp_association.py
> +            self.output = f"\nOutput of {tops.show_cmd} command is: \n{output}"
```suggestion
            self.output = f"Output of {tops.show_cmd} command is: \n{output}\n"
```

2023-08-29 08:48 UTC, MaheshGSLAB commented on nrfu_tests/test_base_services_ntp_association.py
> +                    tops.output_msg += "Primary NTP association is not present on the host.\n"
```suggestion
                    tops.output_msg += "Primary NTP association is not found on the device.\n"
```

2023-08-30 05:33 UTC, MaheshGSLAB requested changes

2023-08-30 05:33 UTC, MaheshGSLAB commented on nrfu_tests/test_base_services_ntp_association.py
> +                tops.output_msg = "\n"
```suggestion
                tops.output_msg = ""
```

2023-08-30 05:49 UTC, MaheshGSLAB approved these changes

2023-08-30 12:01 UTC, vishwajeetgslab requested changes

2023-09-01 08:04 UTC, vishwajeetgslab approved these changes

2023-09-26 14:55 UTC, merged