Issue-446:Convert Pytest-CVP Free Memory test case to Vane
aristanetworks/vane pull request #478
Opened 2023-08-28 12:35 UTC by rahulrajolegslab

# Please include a summary of the changes

test_definition.yaml.j2: Updated J2 with testcase NRFU6.7
master_def.yaml: Updated master def with testcase NRFU6.7
test_definition.yaml: Added test def with testcase NRFU6.7
test_security_rp_ssh_access_list.py: Added python file for testcase NRFU6.7

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on
This testcase will verify the memory utilization of the device. If the memory utilization is greater than expected then testcase should failed otherwise testcase should pass.

# Include the Issue number and link

https://github.com/aristanetworks/vane/issues/446
Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (Convert Pytest-CVP Free Memory test case to Vane)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

Unit test cases:

1. Verified that testcase pass if expected memory utilization in the output.
               
[report_2308281626.docx](https://github.com/aristanetworks/vane/files/12454331/report_2308281626.docx)
[report.zip](https://github.com/aristanetworks/vane/files/12454349/report.zip)

2. Verified that testcase failed if expected memory utilization is not  in the output.

[report_2308281629.docx](https://github.com/aristanetworks/vane/files/12454369/report_2308281629.docx)
[report.zip](https://github.com/aristanetworks/vane/files/12454373/report.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-29 11:15 UTC, AbhijeetGSLAB commented on nrfu_tests/test_system_hardware_free_memory.py
> +@pytest.mark.nrfu_tests
Use marker `nrfu_test`

2023-08-29 11:18 UTC, AbhijeetGSLAB commented on nrfu_tests/test_system_hardware_free_memory.py
> +        except (AssertionError, AttributeError, LookupError, EapiError) as excep:
Please check if assert needs to be added in the testcase. If not please remove AssertionError from here as it is not needed

2023-08-29 11:21 UTC, AbhijeetGSLAB commented on nrfu_tests/test_definition.yaml
> +    test_criteria: The free memory percentage of hostname should be less than 70. # Setting test case’s pass / fail criteria for reporting
`The free memory percentage of the device should be less than 70.`

2023-08-29 11:21 UTC, AbhijeetGSLAB commented on nrfu_tests/test_definition.yaml.j2
> +      criteria: {{ test_data["criteria"] }}
Add an empty line at the end

2023-08-31 05:55 UTC, AbhijeetGSLAB approved these changes

2023-08-31 07:13 UTC, MaheshGSLAB commented
Update the file name
![image](https://github.com/aristanetworks/vane/assets/122076792/8bc77c75-3df0-45ba-ad31-a306a743942b)

2023-08-31 07:15 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    show_cmd: show version
show version command is already running by vane so use the same. No need to run it again

2023-08-31 07:16 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +      memory_utilization: True
```suggestion
      memory_utilization_under_range: True

```

2023-08-31 07:17 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_free_memory.py
> +class SystemHardwareFreeMemoryTests:
```suggestion
class FreeMemoryTests:

```

2023-08-31 07:19 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_free_memory.py
> +                        "The expected memory utilization percentage of the device is not less than"
Memory utilization on device is not correct. Expected memory utilization is below '70%' however in actual found as '80%'.

2023-09-01 05:39 UTC, MaheshGSLAB requested changes

2023-09-01 05:39 UTC, MaheshGSLAB commented on nrfu_tests/master_def.yaml
You deleted this file instead of remove the content. Only content should be removed

2023-09-01 05:39 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    utilization_threshold: 70 # Verification value to verify the memory utilization of the device
As suggested please remove the threshold from test def. It should be hardcoded in python file

2023-09-01 05:39 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +  - name: test_system_hardware_free_memory
```suggestion
  - name: test_system_free_memory

```

2023-09-01 05:39 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    description: Testcase for verification of system hardware free memory functionality.
```suggestion
    description: Testcase for verification of system hardware free memory utilization.

```
update it at all places

2023-09-01 05:39 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_free_memory.py
> +                if not tops.actual_output["memory_utilization_under_range"]:
this second IF condition is not needed as in your case only one key there so the parent if condition is enough

2023-09-01 11:18 UTC, MaheshGSLAB requested changes

2023-09-01 11:18 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_free_memory.py
> +                )
tops.output_msg = (
                    "Memory utilization on device is not correct. Expected memory utilization is"
                    f" below '70%' however in actual found as '{memory_utilization}'."
                )

2023-09-01 11:18 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_free_memory.py
> +            "The expected memory utilization percentage of the device is less than 70%"
```suggestion
            "Memory utilization percentage of the device is less than 70%"

```

2023-09-01 13:15 UTC, MaheshGSLAB approved these changes

2023-09-13 13:18 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_free_memory.py
> +        tops.output_msg = "Memory utilization percentage of the device is less than 70%"
Is it possible to add the current memory utilization so user has a record (without needing to do math)?

2023-09-15 07:06 UTC, rahulrajolegslab commented on nrfu_tests/test_system_hardware_free_memory.py
> +        tops.output_msg = "Memory utilization percentage of the device is less than 70%"
Updated the tops.output_msg with current memory utilization

2023-09-26 15:05 UTC, kgrozis-arista approved these changes

2023-09-26 15:05 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_free_memory.py
> +        tops.output_msg = "Memory utilization percentage of the device is less than 70%"
LGTM

2023-09-26 15:06 UTC, merged