Issue-421: Convert Pytest-CVP SSO test case to Vane
aristanetworks/vane pull request #479
Opened 2023-08-29 05:34 UTC by AbhijeetGSLAB

# Please include a summary of the changes

* test_definition.yaml: Updated test def with testcase NRFU1.3.
* test_definition.yaml.j2: Updated J2 with testcase NRFU1.3.
* master_def.yaml: Updated master def with testcase NRFU1.3.
* test_base_services_redundancy_sso_test.py: Added python file for testcase NRFU1.3.

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link
#421 
Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU Testcase)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

Note: **Tested the test case using the hardcoded output as this testcase is not working on the ACT lab and also on the Tier Point Lab.**

Unit Test Cases:
1. Tested the testcase for pass scenario.

[Pass Reports.zip](https://github.com/aristanetworks/vane/files/12460391/Pass.Reports.zip)

2. Tested the testcase for failure scenario.

[Fail Reports.zip](https://github.com/aristanetworks/vane/files/12460411/Fail.Reports.zip)

3. Tested the testcase for pass scenario using the J2 file.

[Pass Reports J2.zip](https://github.com/aristanetworks/vane/files/12460446/Pass.Reports.J2.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-30 06:44 UTC, geetanjalimanegslab commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +
<img width="487" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/c021119e-ba1b-4ffb-9565-0fcbd92fa4d7">

Are we not considering this check?

2023-08-30 06:44 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +    test_criteria: Redundancy SSO protocol should be configured and operational. # Setting test case’s pass / fail criteria for reporting
```suggestion
    test_criteria: Redundancy SSO protocol should be configured, operational, and ready for switchover. # Setting test case’s pass/fail criteria for reporting
```

2023-08-30 06:44 UTC, geetanjalimanegslab commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +    """
Update unit testcases sentences properly. also add a unit test for SSO not configured.

2023-08-30 06:44 UTC, geetanjalimanegslab commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +                        f" {expected_details['operational_protocol']}, however in actual it is"
<img width="436" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/2eeb542d-b06c-4b65-8369-ac43bdba1f7d">

Highlight the expected and actual output.

2023-09-01 08:24 UTC, geetanjalimanegslab requested changes

2023-09-01 08:24 UTC, geetanjalimanegslab commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +        except (AttributeError, LookupError, EapiError) as excep:
Add assertion Error.

2023-09-01 08:24 UTC, geetanjalimanegslab commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +            """
The assertion error report is empty.
please verify the same after adding the assertion in the execption block.

<img width="437" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/d15e4610-d801-4a6a-a3dc-6b7ddd8a2ef4">

2023-09-01 10:07 UTC, MaheshGSLAB requested changes

2023-09-01 10:07 UTC, MaheshGSLAB commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +            assert (
am not getting this assert properly. if peerstate not inserted then testcase should skip not fail

2023-09-01 11:39 UTC, geetanjalimanegslab commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +import pytest
Please mark your PR as draft

2023-09-04 10:33 UTC, MaheshGSLAB requested changes

2023-09-04 10:33 UTC, MaheshGSLAB commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +        except (AssertionError, AttributeError, LookupError, EapiError) as excep:
no assert hence remove the AssertionError

2023-09-04 10:38 UTC, geetanjalimanegslab approved these changes

2023-09-06 22:59 UTC, rewati-arista requested changes

2023-09-06 22:59 UTC, rewati-arista commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +from vane.logger import logger
use the logger introduced through this PR: https://github.com/aristanetworks/vane/pull/368

2023-09-06 22:59 UTC, rewati-arista commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +        self.output = ""
same suggestion as https://github.com/aristanetworks/vane/pull/485/files#r1316418284

2023-09-06 22:59 UTC, rewati-arista commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +        tops.show_cmd = "show redundancy status"
is there a reason we define show command here instead of definitions file?

2023-09-06 22:59 UTC, rewati-arista commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +                logger.info(
f-string

2023-09-06 22:59 UTC, rewati-arista commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +            logger.error(
f-string

2023-09-06 22:59 UTC, rewati-arista commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +
line 74-104 can follow https://github.com/aristanetworks/vane/pull/485/files#r1316430271

2023-09-14 10:12 UTC, AbhijeetGSLAB commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +        tops.show_cmd = "show redundancy status"
Hi Rewati,
We need to skip this testcase in case of unavailable command. So using the wrapper function to run the show cmd and  catching the exception.If command is added in test definitions file then it returns an empty output hence not able to skip based on it. Let me know your thought.

2023-09-14 10:28 UTC, AbhijeetGSLAB commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +from vane.logger import logger
Updated the logger in the PR. Thanks for the suggestion

2023-09-14 10:30 UTC, AbhijeetGSLAB commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +        self.output = ""
As discussed in the call with Kevin and Shachi, they suggested keeping this change as it is.

2023-09-14 10:31 UTC, AbhijeetGSLAB commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +                logger.info(
Updated the logger using f string in the MR

2023-09-14 10:31 UTC, AbhijeetGSLAB commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +            logger.error(
Updated the logger using f string in the MR

2023-09-14 10:32 UTC, AbhijeetGSLAB commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +
As discussed in the call with Kevin and Shachi, they suggested keeping this change as it is. Thanks

2023-09-18 21:18 UTC, rewati-arista commented on nrfu_tests/test_base_services_redundancy_sso_test.py
> +        tops.show_cmd = "show redundancy status"
Makes sense, thank you for clarifying

2023-09-18 21:19 UTC, rewati-arista approved these changes
LGTM

2023-09-18 21:19 UTC, merged