issue_422: Converted Pytest-CVP TACACS test case to Vane #422
aristanetworks/vane pull request #480
Opened 2023-08-29 06:05 UTC by hsisalgslab

# Please include a summary of the changes

Converted test_base_services_ntp_association.py as per the vane style guide along with that updated following files.
test_definition.yaml: Updated test def with testcase NRFU1.2
test_definition.yaml.j2: Updated J2 with testcase NRFU1.2.
pytest.ini: Added marker nrfu_test and base_services

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link
https://github.com/aristanetworks/vane/issues/422

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (please specify)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?
**Note:Tested with using hardcoded output**
Unit tests and report :

1) Pass_case : Tested that TACACS servers have no errors, timeouts, failures or disconnects.
Reports:
[pass_report.docx](https://github.com/aristanetworks/vane/files/12460788/pass_report.docx)

2) Fail_case : Tested that test case should failed when all TACACS servers details are incorrect 
Reports:

[all_params_fail.docx](https://github.com/aristanetworks/vane/files/12460804/all_params_fail.docx)

3) Fail_case : Tested that test case should failed when few of the TACACS servers details are incorrect 
Reports:

[fail_report.docx](https://github.com/aristanetworks/vane/files/12460813/fail_report.docx)

4) Fail_case : Tested that test case should failed when No TACACS servers are configured on the device.

HTML reports for all mentioned unit testcases:
[HTML zip.zip](https://github.com/aristanetworks/vane/files/12460836/HTML.zip.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-30 07:05 UTC, geetanjalimanegslab commented on nrfu_tests/test_base_services_tacacs.py
> +            else:
remove this else condition

2023-08-30 07:07 UTC, geetanjalimanegslab commented on nrfu_tests/test_base_services_tacacs.py
> +        except (AssertionError, AttributeError, LookupError, EapiError) as excep:
remove assertion error

2023-08-30 07:12 UTC, geetanjalimanegslab commented on nrfu_tests/test_base_services_tacacs.py
> +
<img width="315" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/4f7ac980-eaae-48cf-931c-d5b3bdd1caec">

specify it as nrfu tests

2023-08-30 11:15 UTC, geetanjalimanegslab commented on nrfu_tests/test_base_services_tacacs.py
> +            """
Add report for 
<img width="502" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/c7a0bd6e-550f-41c9-942a-0311ab6fd7b2">

2023-08-30 11:15 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +    report_style: modern ## Setting report_style as modern If report type is set to modern, then it will update steps, assumptions, and external systems in the docx report.
```suggestion
    report_style: modern
```
Remove the inline comments. I think it's not needed here.

2023-09-01 04:36 UTC, hsisalgslab commented on nrfu_tests/test_base_services_tacacs.py
> +            """
This already added in HTML_report.zip

2023-09-01 09:36 UTC, MaheshGSLAB commented
Please check the pipeline, it should not fail

2023-09-01 09:38 UTC, MaheshGSLAB commented
Why input shows as null
![image](https://github.com/aristanetworks/vane/assets/122076792/fd02f9cf-1e73-4385-8617-7895fe91caec)

2023-09-01 09:39 UTC, MaheshGSLAB commented
Expected is always 0 so lets not repeat for each time. We can add it once in heading line
![image](https://github.com/aristanetworks/vane/assets/122076792/d12740ee-4861-4132-8c80-be6a75a3304c)

2023-09-01 09:41 UTC, MaheshGSLAB commented
Can you add the report where found errors on two tacacs servers.
![image](https://github.com/aristanetworks/vane/assets/122076792/4c2e82db-372e-44ee-a3f6-b7bef22c13df)

2023-09-01 09:43 UTC, MaheshGSLAB requested changes

2023-09-01 09:43 UTC, MaheshGSLAB commented on nrfu_tests/master_def.yaml
> +global_dut_filter: # This stanza is optional. If it is not provided by users than all test cases should be run on each dut.
Remove the changes in master def

2023-09-01 09:43 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml.j2
> +      expected_output: null #Forming expected output in test case file.
In J2 comments should be above the variable not in line

2023-09-01 09:43 UTC, MaheshGSLAB commented on nrfu_tests/test_base_services_tacacs.py
> +        TD: Testcase for verification of TACACS servers details.
```suggestion
        TD: Testcase to verify that TACACS servers have no errors, timeouts, failures or disconnects.
```

2023-09-01 13:20 UTC, MaheshGSLAB approved these changes

2023-09-04 10:10 UTC, geetanjalimanegslab approved these changes

2023-09-26 16:37 UTC, merged