issue-442: Convert Pytest-CVP Core Dump test case to Vane
aristanetworks/vane pull request #481
Opened 2023-08-29 07:57 UTC by MaheshGSLAB

# Please include a summary of the changes

* test_definition.yaml
Updated test def with testcase NRFU6.3.
* test_definition.yaml.j2 
Updated J2 with testcase NRFU6.3.
* master_def.yaml
Updated master def with testcase NRFU6.3.
* test_system_hardware_coredump.py
Added python file for testcase NRFU6.3.

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link

https://github.com/aristanetworks/vane/issues/442

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (Convert Pytest-CVP Core Dump test case to Vane)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?
1. Testcase pass when no core dump files are found.
Reports with J2: [report_2308291211_pass_j2_nrfu6.3.docx]https://github.com/aristanetworks/vane/files/12461690/report_2308291211_pass_j2_nrfu6.3.docx)[report_pass_j2_nrfu6.3.html.zip](https://github.com/aristanetworks/vane/files/12461693/report_pass_j2_nrfu6.3.html.zip)

Reports with test def:[report_2308291215_pass_nrfu6.3.docx]https://github.com/aristanetworks/vane/files/12461714/report_2308291215_pass_nrfu6.3.docx)
[report_pass_nrfu6.3.html.zip](https://github.com/aristanetworks/vane/files/12461720/report_pass_nrfu6.3.html.zip)

2. Testcase failed when core dump files are found.
Reports: [report_2308291220_fail_nrfu6.3.docx]https://github.com/aristanetworks/vane/files/12461732/report_2308291220_fail_nrfu6.3.docx)
[report_fail_nrfu6.3.html.zip](https://github.com/aristanetworks/vane/files/12461734/report_fail_nrfu6.3.html.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-29 12:49 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +    - name: test_hardware_core_dump
```suggestion
    - name: test_hardware_core_dump_files
```

2023-08-29 12:49 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +      test_criteria: Core dump files should not found. # Setting test case’s pass / fail criteria for reporting
```suggestion
      test_criteria: Core dump files should not found. # Setting test case’s pass/fail criteria for reporting
```

2023-08-29 12:49 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml.j2
> +      description: Test case to verify that core dump files are not found
```suggestion
      description: Test case for the verification of core dump files are not found.

```

2023-08-29 12:49 UTC, geetanjalimanegslab commented on nrfu_tests/test_system_hardware_coredump.py
> +Test case to verify that core dump files are not found
Updated the same as mentioned above

2023-08-29 12:49 UTC, geetanjalimanegslab commented on nrfu_tests/test_system_hardware_coredump.py
> +        tops.output_msg = "Core dump files are not found."
can we update? please correct me if I am wrong.
```suggestion
        tops.output_msg = "Core dump files are not found on the device."

```

2023-08-29 12:49 UTC, geetanjalimanegslab commented on nrfu_tests/test_system_hardware_coredump.py
> +            self.output += f"Output of {tops.show_cmd} command is:\n{core_dump}"
```suggestion
            self.output = f"Output of {tops.show_cmd} command is:\n{core_dump}"

```

2023-08-29 12:49 UTC, geetanjalimanegslab commented on nrfu_tests/test_system_hardware_coredump.py
> +        except (AssertionError, AttributeError, LookupError, EapiError) as excep:
```suggestion
        except (AttributeError, LookupError, EapiError) as excep:

```

2023-08-31 05:44 UTC, geetanjalimanegslab approved these changes

2023-08-31 08:25 UTC, vishwajeetgslab requested changes

2023-08-31 08:25 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +      description: Test case to verify that core dump files are not found
Test case for verification of core dump files.

2023-08-31 08:25 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +      test_criteria: Core dump files should not found on the device. # Setting test case’s pass/fail criteria for reporting
```suggestion
      test_criteria: Core dump files should not present on the device. # Setting test case’s pass/fail criteria for reporting
```

2023-08-31 08:25 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml.j2
> +        core_dump_files_not_found: True
```suggestion
        core_dump_files_not_present: True

```

2023-08-31 08:25 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_coredump.py
> +            should not found.
```suggestion
            are not present on device.

```

2023-08-31 08:25 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_coredump.py
> +                tops.output_msg = "Core dump files are found on the device."
```suggestion
                tops.output_msg = "Core dump files are present on the device."

```

2023-08-31 10:37 UTC, vishwajeetgslab approved these changes

2023-09-06 23:13 UTC, rewati-arista requested changes

2023-09-06 23:13 UTC, rewati-arista commented on nrfu_tests/test_definition.yaml
> +      test_criteria: Core dump files should not found on the device. # Setting test case’s pass/fail criteria for reporting
typo
```suggestion
      test_criteria: Core dump files should not be found on the device. # Setting test case’s pass/fail criteria for reporting
```

2023-09-06 23:13 UTC, rewati-arista commented on nrfu_tests/test_definition.yaml.j2
> +      test_criteria: Core dump files should not found on the device.
same as above

2023-09-06 23:13 UTC, rewati-arista commented on nrfu_tests/test_system_hardware_coredump.py
> +from vane.logger import logger
use the logger introduced through this PR: https://github.com/aristanetworks/vane/pull/368

2023-09-06 23:13 UTC, rewati-arista commented on nrfu_tests/test_system_hardware_coredump.py
> +        self.output = ""
same suggestion as https://github.com/aristanetworks/vane/pull/485/files#r1316418284

2023-09-06 23:13 UTC, rewati-arista commented on nrfu_tests/test_system_hardware_coredump.py
> +            should not found on the device.
typo
```suggestion
            should not be found on the device.

```

2023-09-06 23:13 UTC, rewati-arista commented on nrfu_tests/test_system_hardware_coredump.py
> +            logger.info(
f-string

2023-09-06 23:13 UTC, rewati-arista commented on nrfu_tests/test_system_hardware_coredump.py
> +            # Output message formation in case of testcase fails.
```suggestion
            # Output message formation in case testcase fails.

```

2023-09-06 23:13 UTC, rewati-arista commented on nrfu_tests/test_system_hardware_coredump.py
> +            logger.error(
f-string

2023-09-14 11:52 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_coredump.py
> +        self.output = ""
As discussed in call keeping as it is

2023-09-19 20:22 UTC, rewati-arista approved these changes
LGTM

2023-09-19 20:22 UTC, merged