issue-20_:Convert Pytest-CVP Fan Status test case to Vane #444
aristanetworks/vane pull request #482
Opened 2023-08-29 08:37 UTC by rohitsinghgslab

# Please include a summary of the changes

Converted test_hardware_fan_status.py as per the vane style guide along with that updated following files.
test_definition.yaml: Updated test def with testcase NRFU6.5
test_definition.yaml.j2 and master_def.yaml : Updated J2 with testcase NRFU6.5

# Any specific logic/part of code you need extra attention on

Verified  power supplies fan status.

# Include the Issue number and link
https://github.com/aristanetworks/vane/issues/444

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (please specify)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?
**Note: Tested with using hardcoded output**
Unit tests and report :

1) Pass_case : Tested that TACACS servers have no errors, timeouts, failures or disconnects.
Reports:
[444_reports.zip](https://github.com/aristanetworks/vane/files/12462119/444_reports.zip)

## Bug fix

    
## New feature
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    
# Additional comments

2023-08-29 10:37 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +Testcases for verification of fan status.
```suggestion
Testcases for verification of system hardware fan status.
```

2023-08-29 10:40 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +    Testcases for verification of fan status.
update as per above comment

2023-08-29 10:40 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +@pytest.mark.nrfu_test
```suggestion
@pytest.mark.nrfu_test
@pytest.mark.system
```
need to add this marker as well

2023-08-29 10:41 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +        TD: Testcases for verification of fan status.
```suggestion
        TD: Testcase for verification system hardware fan status.
```

2023-08-29 10:44 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +    def test_system_hardware_fan_status(self, dut, tests_definitions):
pls update python file name as "test_system_hardware_fan_status.py"

2023-08-29 10:47 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +            test_params = tops.test_parameters
initialize it before try block

2023-08-29 10:48 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +                "On device %s: Output of %s command is: \n%s\n",
```suggestion
                "On device %s, Output of %s command is: \n%s\n",
```

2023-08-29 10:49 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +            TS: Running `show system environment cooling detail` command and collecting
```suggestion
            TS: Running `show system environment cooling detail` command and verifying
```

2023-08-29 11:00 UTC, hsisalgslab commented on nrfu_tests/test_definition.yaml
> +      - fanTraySlots
i guess dont need to add it in test def ..directly can parse from py file.

2023-08-29 11:05 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +                        tops.actual_output["fan_status_details"][power_slots].update(
![image](https://github.com/aristanetworks/vane/assets/122077912/b9ddd10b-de50-4b2a-8377-63f37a364a5b)
we dont use camel casing for output dict keys

2023-08-29 11:06 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +                            f" 80: {fan_label}\n\n"
80 can be taken from test def ?

2023-08-31 04:28 UTC, hsisalgslab commented on nrfu_tests/test_hardware_fan_status.py
> +Testcases for verification of fan status.
This is not addressed

2023-08-31 04:32 UTC, hsisalgslab approved these changes

2023-08-31 06:37 UTC, vishwajeetgslab requested changes

2023-08-31 06:37 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_fan_status.py
> +        tops.actual_output = {"fan_status_details": {}}
can we add it as {fans_slots:  {fan_tray_slots: {}, power_supply_slots:{}}

2023-08-31 06:37 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_fan_status.py
> +            """
"""
TS: Running `show version` commands on the device and skipping the test case if device platform is 'vEOS'.
 """

2023-08-31 06:37 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_fan_status.py
> +                        )
We need to add the current state of fans and speed as well in observation section

2023-09-04 15:57 UTC, vishwajeetgslab requested changes

2023-09-04 15:57 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +  - name: test_system_hardware_fan_status
format properly

2023-09-06 09:49 UTC, vishwajeetgslab approved these changes

2023-09-26 16:26 UTC, kgrozis-arista requested changes

2023-09-26 16:26 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_fan_status.py
> +                        for fan_lable, fan_details in slot_details.items():
Should fan_lable be fan_label?

2023-09-26 16:26 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                    .get(fan_lable)
Should fan_lable be fan_label?

2023-09-26 16:26 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                                f"{fan_lable}: Fan status is 'ok', however current"
Should fan_lable be fan_label?

2023-09-26 16:26 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                            int(fan_speed_details[fan_lable]) > 80
Should fan_lable be fan_label?

2023-09-26 16:26 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                        tops.output_msg += f"{fan_lable}: Fan status is 'Not ok'.\n"
Should fan_lable be fan_label?

2023-09-26 16:26 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                                f" fan speed '{fan_speed_details.get(fan_lable)}'"
Should fan_lable be fan_label?

2023-09-27 06:55 UTC, rohitsinghgslab commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                                f" fan speed '{fan_speed_details.get(fan_lable)}'"
Done

2023-09-27 06:55 UTC, rohitsinghgslab commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                            int(fan_speed_details[fan_lable]) > 80
Done

2023-09-27 06:55 UTC, rohitsinghgslab commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                                f"{fan_lable}: Fan status is 'ok', however current"
Done

2023-09-27 06:56 UTC, rohitsinghgslab commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                    .get(fan_lable)
Done

2023-09-27 06:56 UTC, rohitsinghgslab commented on nrfu_tests/test_system_hardware_fan_status.py
> +                        for fan_lable, fan_details in slot_details.items():
Done, thanks

2023-09-27 12:51 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_fan_status.py
> +                        for fan_lable, fan_details in slot_details.items():
lgtm

2023-09-27 12:52 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                                f"{fan_lable}: Fan status is 'ok', however current"
lgtm

2023-09-27 12:52 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_fan_status.py
> +                                        tops.output_msg += f"{fan_lable}: Fan status is 'Not ok'.\n"
lgtm

2023-09-27 12:53 UTC, kgrozis-arista approved these changes

2023-09-27 12:53 UTC, merged