Issue 7
aristanetworks/vane pull request #483
Opened 2023-08-29 10:04 UTC by Ashutosh-GSLAB

# Please include a summary of the changes

test_definition.yaml: Updated test def with testcase NRFU6.11
test_definition.yaml.j2: Updated J2 with testcase NRFU6.11
master_def.yaml: Updated master def with testcase NRFU6.11
test_security_rp_ssh_access_list.py: Added python file for testcase NRFU6.11

# Any specific logic/part of code you need extra attention on

validating system temperature sensors details

# Include the Issue number and link
#450 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [X] Other (NRFU testcases)

# Effort required on reviewers end

- - [ ] Easy
- - [X] Medium
- - [ ] Hard 

# How Has This Been Tested?
Note: Tested with using hardcoded output
Unit tests and report :
[Uploading validate_system_temperature_sensors.zip…]()

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-30 08:11 UTC, AbhijeetGSLAB commented on nrfu_tests/master_def.yaml
> +common_data:
Update the master def as per placeholder MR

2023-08-30 08:12 UTC, AbhijeetGSLAB commented on nrfu_tests/test_system_temperature_sensors.py
> +# Copyright (c) 2022 Arista Networks, Inc.  All rights reserved.
```suggestion
# Copyright (c) 2023Arista Networks, Inc.  All rights reserved.

```

2023-08-30 08:25 UTC, AbhijeetGSLAB commented on nrfu_tests/test_system_temperature_sensors.py
> +                                "temp_is_getting_high": temp_status,
The key can be temperature_status

2023-08-30 08:27 UTC, AbhijeetGSLAB commented on nrfu_tests/test_system_temperature_sensors.py
> +    def test_validate_system_temperature_sensors(self, dut, tests_definitions):
```suggestion
    def test_system_temperature_sensors(self, dut, tests_definitions):

```

2023-08-31 10:26 UTC, vishwajeetgslab requested changes

2023-08-31 10:26 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_temperature.py
> +        tops.actual_output = {"temp_sensors": {}, "power_supplies_sensors": {}}
```suggestion
        tops.actual_output = {"sensors": {"temperature_sensors": {}, "power_supply_sensors": {}}}

```

2023-08-31 10:26 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_temperature.py
> +            self.output += f"\n\nOutput of 'show version' command is: \n{version_output}"
```suggestion
            self.output += f"\nOutput of 'show version' command is: \n{version_output}"

```

2023-08-31 10:26 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_temperature.py
> +                    )
Can this repeated loop be avoided.

2023-08-31 10:26 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_temperature.py
> +                        {description: {"temp_is_getting_high": True}}
```suggestion
                        {description: {"overheat_threshold_met": False}}

```

2023-08-31 10:26 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_temperature.py
> +                "On device %s: Output of 'show version' command is: \n%s\n",
```suggestion
                "On device %s, Output of 'show version' command is: \n%s\n",

```

2023-09-06 12:09 UTC, vishwajeetgslab requested changes

2023-09-06 12:09 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_temperature.py
> +                    if details_value == actual_sensor:
```suggestion
                    if expected_sensor_details == actual_sensor_details :

```

2023-09-06 15:04 UTC, AbhijeetGSLAB approved these changes

2023-09-08 05:43 UTC, geetanjalimanegslab commented on nrfu_tests/test_system_hardware_temperature.py
> +                    output_msg += f"For {sensor_detail}:"
```suggestion
                    output_msg += f"{sensor_detail}:"

```

2023-09-08 05:43 UTC, geetanjalimanegslab commented on nrfu_tests/test_system_hardware_temperature.py
> +                        " than Threshold temperature"
```suggestion
                        " than threshold temperature"

```

2023-09-08 07:16 UTC, Ashutosh-GSLAB commented on nrfu_tests/test_system_hardware_temperature.py
> +        current_temperature = sensor_detail["currentTemperature"]
we will get the current temperature always. so I thing we can access it without using get method.

2023-09-08 10:56 UTC, geetanjalimanegslab approved these changes

2023-09-14 13:29 UTC, vishwajeetgslab approved these changes

2023-09-26 16:35 UTC, kgrozis-arista approved these changes

2023-09-26 17:11 UTC, merged