Issue_428: Convert Pytest-CVP Port-Channel test case to Vane #428
aristanetworks/vane pull request #484
Opened 2023-08-29 11:33 UTC by geetanjalimanegslab

# Please include a summary of the changes

Converted test_interfaces_port_channels.py as per the vane style guide along with the updated following files.
test_definition.yaml: Updated test def with testcase NRFU2.6
test_definition.yaml.j2: Updated J2 with testcase NRFU2.6
pytest.ini: Added marker nrfu_test and interfaces
masterdef.yaml: Added master def yaml for DUTs

# Any specific logic/part of code you need extra attention on
   From the output of  **show lacp interface all-ports**,  verified that the all port-channel interface members are collecting and distributing , if port channels are not found then testcase will skip.

# Include the Issue number and link
https://github.com/aristanetworks/vane/issues/428

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU testcases)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?
Unit testcases:
 - Tested the same testcase with all portchannel interface members collecting and distributing: Passed
    Report:
    [report_po_pass.docx](https://github.com/aristanetworks/vane/files/12463971/report_po_pass.docx)

- Tested with portchannel details are not found on the device: Skipped
  Reports:
  [report_po_skipped.docx](https://github.com/aristanetworks/vane/files/12463978/report_po_skipped.docx)

- Tested with a few portchannel interface members are not collecting and distributing: Failed
  Reports:
  [report_po_failed.docx](https://github.com/aristanetworks/vane/files/12463984/report_po_failed.docx)

HTML reports:
[ps_po.zip](https://github.com/aristanetworks/vane/files/12463991/ps_po.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-30 10:43 UTC, MaheshGSLAB requested changes

2023-08-30 10:43 UTC, MaheshGSLAB commented on nrfu_tests/master_def.yaml
> +  NRFU2.6: {}
testcase_data:
  NRFU2.6: {}
  
  Not required

2023-08-30 10:43 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    description: Testcases for the verification of port channel interface member details should be collecting and distributing.
```suggestion
    description: Testcases for the verification of port channel member interfaces should be collecting and distributing.
```

2023-08-30 10:43 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_port_channels.py
> +            for port_channel, po_data in output.get("portChannels").items():
```
for portChannel in portChannels:
            for interface in portChannels[portChannel]['interfaces']:
                collecting = portChannels[portChannel]['interfaces'][interface]['actorPortState']['collecting']
                distributing = portChannels[portChannel]['interfaces'][interface]['actorPortState']['distributing']

```
We wont need the po_data if use the above logic

2023-08-30 10:43 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_port_channels.py
> +                    tops.test_parameters["partner_port_state"] = {
please avoid to use tops.test_parameters for assigning values

2023-08-30 10:43 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_port_channels.py
> +                for port_channel, po_data in tops.actual_output["port_channels"].items():
```suggestion
                for port_channel, port_channel_data in tops.actual_output["port_channels"].items():
```

2023-08-30 10:43 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_port_channels.py
> +                    no_collecting_state_interface = []
```suggestion
                    not_collecting_interfaces = []
```

2023-08-30 10:43 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_port_channels.py
> +                    no_distributing_state_interface = []
```suggestion
                    not_distributing_interfaces = []
```

2023-08-30 10:43 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_port_channels.py
> +                            "following interface members are not distributing :"
```suggestion
                            "following member interfaces are not distributing :"
```

2023-09-01 11:02 UTC, MaheshGSLAB commented
Please use member interfaces 
![image](https://github.com/aristanetworks/vane/assets/122076792/d676096f-620e-4fbd-9b81-9c81701789eb)

2023-09-01 11:02 UTC, MaheshGSLAB requested changes

2023-09-04 08:14 UTC, vishwajeetgslab requested changes

2023-09-04 08:14 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +  - name: test_port_channel_interface_member_details
```suggestion
  - name: test_port_channel_member_interface_details
```

Also please check formatting of parameter in test definitions.

2023-09-04 08:14 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +    test_criteria: All the port channel interface members should be collecting and distributing. # Setting test case’s pass/fail criteria for reporting
```suggestion
    test_criteria: All the port channel members interfaces should be collecting and distributing. # Setting test case’s pass/fail criteria for reporting
```

2023-09-04 08:14 UTC, vishwajeetgslab commented on nrfu_tests/test_interfaces_port_channels.py
> +                        interface_data[interface].get("partnerPortState", {}).get("distributing")
Create a variable for partner_port_state and use it in dictionary.,

2023-09-04 08:14 UTC, vishwajeetgslab commented on nrfu_tests/test_interfaces_port_channels.py
> +                            not_distributing_interfaces.append(interface)
Are we adding the current state of member interface here ?

2023-09-05 08:18 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_port_channels.py
> +                            not_distributing_interfaces.append(interface)
We are verifying the collecting and distributing state only.

2023-09-05 12:21 UTC, MaheshGSLAB approved these changes

2023-09-06 20:53 UTC, rewati-arista requested changes

2023-09-06 20:53 UTC, rewati-arista commented on nrfu_tests/test_definition.yaml
> +    description: Testcases for the verification of port channel member interfaces should be collecting and distributing.
```suggestion
    description: Testcases to verify that port channel member interfaces should be collecting and distributing.
```

2023-09-06 20:53 UTC, rewati-arista commented on nrfu_tests/test_definition.yaml.j2
> +      description: Testcases for the verification of port channel member interfaces should be collecting and distributing.
```suggestion
      description: Testcases to verify that port channel member interfaces should be collecting and distributing.
```

2023-09-06 20:53 UTC, rewati-arista commented on nrfu_tests/test_interfaces_port_channels.py
> +from vane.logger import logger
use the logger introduced through this PR: https://github.com/aristanetworks/vane/pull/368

2023-09-06 20:53 UTC, rewati-arista commented on nrfu_tests/test_interfaces_port_channels.py
> +        TD: Testcases for the verification of port channel members interfaces should
```suggestion
        TD: Testcases to verify that port channel members interfaces should
```

2023-09-06 20:53 UTC, rewati-arista commented on nrfu_tests/test_interfaces_port_channels.py
> +        self.output = ""
same as https://github.com/aristanetworks/vane/pull/485/files#r1316418284

2023-09-06 20:53 UTC, rewati-arista commented on nrfu_tests/test_interfaces_port_channels.py
> +            logger.info(
f - string

2023-09-06 20:53 UTC, rewati-arista commented on nrfu_tests/test_interfaces_port_channels.py
> +            logger.error(
f - string

2023-09-06 20:53 UTC, rewati-arista commented on nrfu_tests/test_interfaces_port_channels.py
> +            # Forming output message if test result is fail
Over here as well, is there a reason we do line 92-100 below, cant we just do that in the previous for instead of having to go through in loops again? like cant we start maintaining not_collecting and not_distributing interfaces within the nested for earlier? and we can add interfaces to them after line 80 by adding a check there itself? the part of putting the output message can happen below, but forming the interfaces can happen earlier imo

I might be missing something here, if there is a reason to do it this way?

2023-09-06 20:53 UTC, rewati-arista commented on nrfu_tests/test_interfaces_port_channels.py
> +
lines after this can follow suggestion https://github.com/aristanetworks/vane/pull/485/files#r1316430271 for tighter try blocks

2023-09-12 11:15 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +    description: Testcases for the verification of port channel member interfaces should be collecting and distributing.
Thanks for the suggestion, Addressed.

2023-09-12 11:15 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml.j2
> +      description: Testcases for the verification of port channel member interfaces should be collecting and distributing.
Addressed.

2023-09-12 11:16 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_port_channels.py
> +from vane.logger import logger
Updated test case with the new logger change.

2023-09-12 11:17 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_port_channels.py
> +        TD: Testcases for the verification of port channel members interfaces should
Addressed comment. 
Thanks

2023-09-12 11:24 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_port_channels.py
> +        self.output = ""
As discussed with Kevin, not updating this change, Once the vane issue is fixed for generating a report we can remove this self. output.
Thanks,
Geetanjali

2023-09-12 11:24 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_port_channels.py
> +            logger.error(
Updated logger with f-string

2023-09-12 11:25 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_port_channels.py
> +            # Forming output message if test result is fail
As discussed in the call with Kevin and Shachi, they suggested keeping this change as it is.

2023-09-12 11:27 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_port_channels.py
> +
As discussed in the call with Kevin and Shachi, they suggested keeping this change as it is.

2023-09-18 21:14 UTC, rewati-arista approved these changes
LGTM

2023-09-18 21:14 UTC, merged