Issue-426:Convert Pytest-CVP MLAG status check test case to Vane #426
aristanetworks/vane pull request #485
Opened 2023-08-29 14:54 UTC by paragpande24

# Please include a summary of the changes

Describe the solution you'd like
PyTest-CVP MLAG status check test case should have the following:

Use Vane test case styling
Use Master definition file to simplify input
Add test case steps to the test case
Test case should be skipped if MLAG is not configured
Test should be added to top-level directory nrfu_tests
Use markers nrfu_test, interfaces
Use Test ID: NRFU2.4

# Any specific logic/part of code you need extra attention on
   From the output of  **show mlag**,  verified that the mlag status is displayed.

# Include the Issue number and link
https://github.com/aristanetworks/vane/issues/426

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU testcases)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?
Unit testcases:

 - Tested the same testcase The mlag status is displayed.: Passed

- Tested with The mlag status is displayed. are not found on the device: Skipped

- Tested with MLAG details are not found: Assert
  
- Tested the mlag status is not displayed (Tested with Hardcode output): Failed

[All_Reports.zip](https://github.com/aristanetworks/vane/files/12465937/All_Reports.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-30 09:09 UTC, AbhijeetGSLAB commented on nrfu_tests/master_def.yaml
> +common_data:
Update it as per placeholder

2023-08-30 09:10 UTC, AbhijeetGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +# Copyright (c) 2022 Arista Networks, Inc.  All rights reserved.
```suggestion
# Copyright (c) 2023 Arista Networks, Inc.  All rights reserved.

```

2023-08-30 09:10 UTC, AbhijeetGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +@pytest.mark.nrfu_tests
```suggestion
@pytest.mark.nrfu_test

```

2023-08-30 09:13 UTC, AbhijeetGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +            TS: Running 'show mlag' command on DUT and verifying the mlag status.
```suggestion
            TS: Running 'show mlag' command on DUT and verifying that the MLAG is configured on the device.

```

2023-08-30 09:16 UTC, AbhijeetGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +        tops.output_msg = "The mlag status is displayed."
```suggestion
        tops.output_msg = "MLAG is configured on the device."

```
Update at all relevant places

2023-08-31 07:30 UTC, MaheshGSLAB commented on nrfu_tests/master_def.yaml
> +global_dut_filter: # This stanza is optional. If it is not provided by users than all test cases should be run on each dut.
lets remove this master def file

2023-08-31 07:31 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    description: Testcase for verification of mlag interfaces status check.
```suggestion
    description: Testcase for verification of MLAG functionality.
```

2023-08-31 07:32 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    test_criteria: MLAG should be configured on the device. # Setting test case’s pass / fail criteria for reporting
```suggestion
    test_criteria: MLAG should be configured as active, connected and consistent on the device . # Setting test case’s pass / fail criteria for reporting
```

2023-08-31 07:33 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +class InterfacesMlagStatusCheckTests:
```suggestion
class MlagStatusTests:

```

2023-08-31 07:33 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +    Testcase for verification of mlag interfaces status check.
update as per test def comment

2023-08-31 07:34 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +        TD: Testcase for verification of mlag interfaces status check.
Update as per test def comment

2023-08-31 07:37 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +        tops.output_msg = "MLAG is configured on the device."
updated as per test def comment

2023-08-31 07:38 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +                        "negStatus": output.get("negStatus"),
```suggestion
                        "negotiation_status": output.get("negStatus"),

```

2023-08-31 07:38 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +                        "configSanity": output.get("configSanity"),
```suggestion
                        "config_sanity": output.get("configSanity"),

```

2023-08-31 07:44 UTC, MaheshGSLAB commented
![image](https://github.com/aristanetworks/vane/assets/122076792/29bd1de5-b711-47cf-9c02-02d93bd2144e)


Expected MLAG state is 'active', however actual found as 'unactive'.
Expected MLAG negotiation status is 'connected', however actual found as 'disconnected'.
Expected MLAG config sanity is 'consistent', however actual found as 'idel'.

2023-08-31 07:49 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +            assert output, "MLAG details are not found"
dont know that this assert is valid or not. Can you please check on multiple device if we can find no mlag details.

2023-09-01 09:28 UTC, MaheshGSLAB requested changes

2023-09-01 09:28 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +  - name: test_interfaces_mlag_status_check
```suggestion
  - name: test_interfaces_mlag_status
```

2023-09-01 09:28 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +                tops.output_msg = ""
```suggestion
                tops.output_msg = "\n"

```

2023-09-01 11:07 UTC, MaheshGSLAB approved these changes

2023-09-01 11:10 UTC, AbhijeetGSLAB approved these changes

2023-09-05 22:03 UTC, rewati-arista requested changes

2023-09-13 12:46 UTC, paragpande24 commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +            logger.info(
Addressed comment.

2023-09-13 12:46 UTC, paragpande24 commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +            logger.error(
Addressed comment.

2023-09-13 12:47 UTC, paragpande24 commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +            self.output += f"\nOutput of {tops.show_cmd} command is: \n{output}"
As discussed with Kevin, not updating this change, Once the vane issue is fixed for generating a report we can remove this self. output.

2023-09-13 12:48 UTC, paragpande24 commented on nrfu_tests/test_interfaces_mlag_status_check.py
> +            output = dut["output"][tops.show_cmd]["json"]
As discussed in the call with Kevin and Shachi, they suggested keeping this change as it is.

2023-09-18 21:11 UTC, merged