issue-431:Convert Pytest-CVP IP Peers Established test case to Vane
aristanetworks/vane pull request #490
Opened 2023-08-30 08:16 UTC by rohitsinghgslab

# Please include a summary of the changes

test_definition.yaml: Updated test def with testcase NRFU4.2
test_definition.yaml.j2: Updated J2 with testcase NRFU4.2
master_def.yaml: Updated master def with testcase NRFU4.2
test_syslog_functionality.py: Added python file for testcase NRFU4.2

# Any specific logic/part of code you need extra attention on

validating BGP ipv4 peers are established.

# Include the Issue number and link
#431 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [X] Other (NRFU testcases)

# Effort required on reviewers end

- - [ ] Easy
- - [X] Medium
- - [ ] Hard 

# How Has This Been Tested?
**Note: Tested on ACT, only failed case is tested on hard - coded.**
Unit tests and reports :
[Vane_PS_431.zip](https://github.com/aristanetworks/vane/files/12473325/Vane_PS_431.zip)

## Bug fix

    
## New feature

 
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

  
    
# Additional comments

2023-08-30 09:38 UTC, hsisalgslab commented on nrfu_tests/master_def.yaml
> +      - BLFE1
update as per latest placeholder MR

2023-08-30 09:43 UTC, hsisalgslab commented on nrfu_tests/test_bgp_peers_state.py
> +        tops.output_msg = "All BGP peers are in established state."
```suggestion
        tops.output_msg = "All BGP IPv4 peers are in established state."
```

2023-08-30 09:44 UTC, hsisalgslab commented on nrfu_tests/test_bgp_peers_state.py
> +            state of BGP peers.
```suggestion
            state of BGP IPv4 peers.
```

2023-08-30 09:48 UTC, hsisalgslab commented on nrfu_tests/test_bgp_peers_state.py
> +            assert bgp_peers, "BGP peers details are not found."
```suggestion
            assert bgp_peers, "BGP peer details are not found."
```

2023-08-30 09:48 UTC, hsisalgslab commented on nrfu_tests/test_bgp_peers_state.py
> +                            f"For the BGP peer '{interface}':\nExpected peer state is {peer_state},"
```suggestion
                            f"For the BGP peer '{interface}':\nExpected peer state is '{peer_state}',"
```

2023-08-30 09:51 UTC, hsisalgslab commented on nrfu_tests/test_bgp_peers_state.py
> +                            f" {tops.actual_output['bgp_peers'].get(interface)}.\n\n"
```suggestion
                            f" '{tops.actual_output['bgp_peers'].get(interface)}'.\n\n"
```

2023-08-31 04:43 UTC, hsisalgslab approved these changes

2023-08-31 09:59 UTC, geetanjalimanegslab requested changes

2023-08-31 09:59 UTC, geetanjalimanegslab commented on nrfu_tests/master_def.yaml
> +  filter:
As discussed  no need of this file.

2023-08-31 09:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_bgp_peers_state.py
> +Testcase for verification of BGP IPv4 peers are established.
Update the same at all other places as well.
```suggestion
Testcase for verification of BGP IPv4 peers state.
```

2023-08-31 09:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_bgp_peers_state.py
> +            self.output = f"\nOutput of {tops.show_cmd} command is:\n{output}\n"
```suggestion
            self.output = f"Output of {tops.show_cmd} command is:\n{output}\n"
```

2023-08-31 09:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_bgp_peers_state.py
> +                    tops.expected_output["bgp_peers"].update({peer: "Established"})
Add this line  tops.expected_output["bgp_peers"].update({peer: "Established"}) just after the 2nd for loop on line number 63

2023-08-31 09:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_bgp_peers_state.py
> +                            f" '{tops.actual_output['bgp_peers'].get(interface)}'.\n\n"
can we use a variable to store the   `tops.actual_output['bgp_peers'].get(interface)`

2023-08-31 09:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml.j2
> +      filter: {{ global_dut_filter.filter }}
please confirm that the new line is added at the end of the file.

2023-08-31 09:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_bgp_peers_state.py
> +                            " however actual found as"
```suggestion
                            " however actual is found as"
```

2023-08-31 09:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_bgp_peers_state.py
> +    test_ids = dut_parameters["test_bgp_ipv4_peers_state"]["ids"]
Add report for assertion failures.

2023-09-01 09:12 UTC, geetanjalimanegslab requested changes

2023-09-01 09:12 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml.j2
> +
the extra line is added.

2023-09-01 09:19 UTC, geetanjalimanegslab requested changes

2023-09-01 09:19 UTC, geetanjalimanegslab commented on nrfu_tests/test_bgp_peers_state.py
> +            output = tops.run_show_cmds([tops.show_cmd])
Why do we need to run the show cmd again? as we are collecting the output of same in the test def yaml

2023-09-01 11:40 UTC, geetanjalimanegslab commented on nrfu_tests/test_bgp_peers_state.py
> +import pytest
please mark PR as draft

2023-09-01 12:27 UTC, rohitsinghgslab commented on nrfu_tests/test_bgp_peers_state.py
> +import pytest
marked

2023-09-04 10:15 UTC, geetanjalimanegslab approved these changes

2023-09-04 13:27 UTC, MaheshGSLAB commented on nrfu_tests/test_bgp_peers_state.py
> +            state of BGP IPv4 peers.
```suggestion
            TS: Running `show ip bgp summary vrf all` command on dut and verifying
            state for all BGP IPv4 peers.
```

2023-09-04 13:33 UTC, MaheshGSLAB commented on nrfu_tests/test_bgp_peers_state.py
> +            if not bgp_peers:
Testcase should skip if peers are not found in any VRF
![image](https://github.com/aristanetworks/vane/assets/122076792/4cd875f9-11f9-4894-bf36-fe9132a68e65)

2023-09-04 13:36 UTC, MaheshGSLAB commented on nrfu_tests/test_bgp_peers_state.py
> +        except (AssertionError, AttributeError, LookupError, EapiError) as excep:
there is no assert so remove AssertionError exception

2023-09-04 13:38 UTC, MaheshGSLAB commented on nrfu_tests/test_bgp_peers_state.py
> +                            f"For the BGP peer {interface}:\nExpected peer state is"
Dut output and observation is not matching. You can change the config get the proper dut output and observation, No need to use hardcode output
![image](https://github.com/aristanetworks/vane/assets/122076792/6f109b87-061c-42ac-a999-d56a9b545515)

2023-09-05 10:41 UTC, MaheshGSLAB requested changes

2023-09-05 10:41 UTC, MaheshGSLAB commented on nrfu_tests/test_bgp_peers_state.py
> +                    bgp_peers_found = True
if you get True in first VRF only then no need to check other VRF so add a break

2023-09-05 10:41 UTC, MaheshGSLAB commented on nrfu_tests/test_bgp_peers_state.py
> +                pytest.skip(f"For {tops.dut_name}, no IP BGP peers configured.")
```suggestion
                pytest.skip(f"For {tops.dut_name}, BGP peers are not found hence skipped the testcase.")
```

2023-09-05 10:41 UTC, MaheshGSLAB commented on nrfu_tests/test_bgp_peers_state.py
> +                        tops.output_msg += (
Form the observation as below. Suggested format was from Kevin
![image](https://github.com/aristanetworks/vane/assets/122076792/ef176012-7254-4cbf-b5bd-6e6f569203aa)

2023-09-05 10:41 UTC, MaheshGSLAB commented on nrfu_tests/test_bgp_peers_state.py
> +                        tops.output_msg += (
BGP neighbors state for following peers is not Established:
Neighbor 172.31.255.0 state is idel
Neighbor 172.31.255.2 state is active

2023-09-06 05:23 UTC, MaheshGSLAB requested changes

2023-09-06 05:23 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +- name: nrfu_tests
resolve the conflicts

2023-09-06 05:23 UTC, MaheshGSLAB commented on nrfu_tests/test_bgp_peers_state.py
> +            if not bgp_peers_found:
awaiting update from Kevin about testcase should fail or skip in case no peers found

2023-09-06 09:05 UTC, rohitsinghgslab commented on nrfu_tests/test_definition.yaml
> +- name: nrfu_tests
resolved it. FYI @MaheshGSLAB

2023-09-06 09:05 UTC, rohitsinghgslab commented on nrfu_tests/test_bgp_peers_state.py
> +            if not bgp_peers_found:
okay

2023-09-15 12:10 UTC, MaheshGSLAB approved these changes

2023-09-26 16:18 UTC, kgrozis-arista approved these changes

2023-09-26 16:18 UTC, merged