Added TC for NRFU2.2 interface status error disabled status
aristanetworks/vane pull request #491
Opened 2023-08-30 08:45 UTC by vitthalmagadum

# Added TC for NRFU2.2 interface status error disabled status

# Issue_ID: https://github.com/aristanetworks/vane/issues/424

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [X] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [ ] Other (please specify)

# Effort required on reviewers end

- - [X] Easy
- - [ ] Medium
- - [ ] Hard 

   
# Reports

[report_passed.docx](https://github.com/aristanetworks/vane/files/12473601/report_passed.docx)

[report_failed.docx](https://github.com/aristanetworks/vane/files/12473606/report_failed.docx)

2023-08-30 11:53 UTC, AbhijeetGSLAB commented on nrfu_tests/test_definition.yaml.j2
> +- name: nrfu_tests
Add an empty line at the end of the file

2023-08-30 11:58 UTC, AbhijeetGSLAB commented on nrfu_tests/test_interfaces_errdisabled.py
> +                        f"\n{interface},\nDescription: {description} and Causes: {causes}"
```suggestion
                        f"\n{interface}:\nDescription: {description} and cause: {causes}"
```

2023-08-31 09:04 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_errdisabled.py
> +                        f"\n{interface}:\nDescription: {description} and cause: {causes}."
can we update?
```suggestion
                        f"\n{interface}:\nDescription: {description} and cause is {causes}."
```

2023-08-31 09:04 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_errdisabled.py
> +                tops.output_msg = "\nFollowing interfaces are in errdisabled state:"
<img width="449" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/1a473efd-7e2e-44ca-8101-84cdc8d3db6c">

can we update actual and expected output  as
`{'interface_state_details': {'Ethernet4': {error_disabled: True}}, {'Ethernet4': {error_disabled: False}}}
`

2023-08-31 09:10 UTC, vitthalmagadum commented on nrfu_tests/test_interfaces_errdisabled.py
> +                tops.output_msg = "\nFollowing interfaces are in errdisabled state:"
No. We don't have interface details in command output in case none of the interface is in error disabled state.

2023-08-31 13:10 UTC, AbhijeetGSLAB approved these changes

2023-08-31 13:47 UTC, geetanjalimanegslab approved these changes

2023-09-01 07:43 UTC, MaheshGSLAB commented
We dont need the description, just cause in enough is same line of itnerface
![image](https://github.com/aristanetworks/vane/assets/122076792/b44bfadf-a67e-48a2-b490-7785b3b56ca5)

2023-09-01 07:45 UTC, MaheshGSLAB commented
Add the report with J2 run

2023-09-01 11:42 UTC, MaheshGSLAB approved these changes

2023-09-06 23:17 UTC, rewati-arista requested changes

2023-09-06 23:17 UTC, rewati-arista commented on nrfu_tests/test_interfaces_errdisabled.py
> +from vane.logger import logger
use the logger introduced through this PR: https://github.com/aristanetworks/vane/pull/368

2023-09-06 23:17 UTC, rewati-arista commented on nrfu_tests/test_interfaces_errdisabled.py
> +        self.output = ""
same suggestion as https://github.com/aristanetworks/vane/pull/485/files#r1316418284

2023-09-06 23:17 UTC, rewati-arista commented on nrfu_tests/test_interfaces_errdisabled.py
> +            logger.error(
f-string

2023-09-06 23:17 UTC, rewati-arista commented on nrfu_tests/test_interfaces_errdisabled.py
> +            tops.expected_output["interface_state_details"] = {
same suggestion as https://github.com/aristanetworks/vane/pull/485/files#r1316430271 for lines 55-72

2023-09-06 23:17 UTC, rewati-arista commented on nrfu_tests/test_interfaces_errdisabled.py
> +            logger.info(
f-string

2023-09-14 08:59 UTC, vitthalmagadum commented on nrfu_tests/test_interfaces_errdisabled.py
> +            tops.expected_output["interface_state_details"] = {
As discussed in the call with Kevin and Shachi, they suggested keeping this change as it is.

2023-09-14 09:00 UTC, vitthalmagadum commented on nrfu_tests/test_interfaces_errdisabled.py
> +        self.output = ""
As discussed in the call with Kevin and Shachi, they suggested keeping this change as it is.

2023-09-14 09:01 UTC, vitthalmagadum commented on nrfu_tests/test_interfaces_errdisabled.py
> +            tops.expected_output["interface_state_details"] = {
As discussed in the call with Kevin and Shachi, they suggested keeping this change as it is.

2023-09-18 20:56 UTC, rewati-arista approved these changes
LGTM

2023-09-18 20:58 UTC, rewati-arista commented
@MaheshGSLAB the linter is failing (flake8 is complaining of longer lines, can you change that so we can merge this in)

2023-09-20 02:45 UTC, vitthalmagadum commented
> @MaheshGSLAB the linter is failing (flake8 is complaining of longer lines, can you change that so we can merge this in)

@rewati-arista I have fixed the flake8 complaints. Please check. Thanks!!

2023-09-20 15:48 UTC, merged