Issue_438: Convert Pytest-CVP Telnet Disabled test case to Vane
aristanetworks/vane pull request #492
Opened 2023-08-30 09:45 UTC by geetanjalimanegslab

# Please include a summary of the changes
Converted test_base_services_ntp_association.py as per the vane style guide along with that updated following files.
test_definition.yaml: Updated test def with testcase NRFU5.7
test_definition.yaml.j2: Updated J2 with testcase NRFU5.7
pytest.ini: Added marker nrfu_test and base_services
nrfu_tests/nrfu_tests/test_security_rp_telnet_disabled.py: Added testcase for NRFU5.7
masterdef.yaml: Updated master def file with global filter.

# Any specific logic/part of code you need extra attention on
 From the output of  'show management telnet' or 'show management telnet vrf <vrf name>',  Verified that the the TELNET state is disabled for all the VRFs on DUT. 
 

# Include the Issue number and link
#438 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU Testcase)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?
Unit Tests:
 **Tested all the scenarios with hardcoded output.**
- Tested for all the VRFS Telnet state is disabled: Passed
  [report_telnet_pass.docx](https://github.com/aristanetworks/vane/files/12474265/report_telnet_pass.docx)

- Tested if a few VRF's Telnet is enabled: Failed.
  [report_telnet_fail.docx](https://github.com/aristanetworks/vane/files/12474268/report_telnet_fail.docx)

- Tested  for all the VRFS Telnet state is disabled: Passed (With generate test definition false )
   [report_telnet_pass_without_j2.docx](https://github.com/aristanetworks/vane/files/12474259/report_telnet_pass_without_j2.docx)

HTML reports:
[telnet.zip](https://github.com/aristanetworks/vane/files/12474276/telnet.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-31 06:53 UTC, MaheshGSLAB requested changes

2023-08-31 06:53 UTC, MaheshGSLAB commented on nrfu_tests/master_def.yaml
> +global_dut_filter: # This stanza is optional. If it is not provided by users than all test cases should be run on each dut.
lets remove this master def

2023-08-31 06:53 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_telnet_disabled.py
> +        tops.expected_output = {"vrfs_telnet_state": {}}
lets form the actual and expected output in below format
```
vrfs:
  default:
    telnet_state: diabled
  DVT:
    telnet_state: enabled
```

2023-08-31 06:53 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_telnet_disabled.py
> +            self.output = f"Output of {tops.show_cmd} command is: \n{output}\n"
```suggestion
            self.output += f"Output of {tops.show_cmd} command is: \n{output}\n"
```

2023-08-31 06:53 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_telnet_disabled.py
> +                if vrf == "default":
```
telnet_cmd = "show management telnet"
if vrf != "default":
  telnet_cmd = f"show management telnet vrf {vrf}"
```

2023-08-31 06:53 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_telnet_disabled.py
> +                self.output = f"Output of {telnet_cmd} command is: \n{cmd_output}\n"
```suggestion
                self.output += f"Output of {telnet_cmd} command is: \n{cmd_output}\n"
```

2023-08-31 06:53 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_telnet_disabled.py
> +                cmd_output = tops.run_show_cmds([telnet_cmd])
Add this command into nested try and exception block

2023-08-31 06:53 UTC, MaheshGSLAB commented on pytest.ini
> +    nrfu_test: Network Ready For Use test cases
lets remove this pytest.ini changes

2023-09-04 10:20 UTC, MaheshGSLAB requested changes

2023-09-04 10:20 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    description: Test case for verification TELNET state as disabled for all the vrfs on DUT.
```suggestion
    description: Test case to verify that Telnet state as disabled for all the VRFs on DUT.
```

2023-09-04 10:20 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_telnet_disabled.py
> +                    "Following VRFs are not configured on the device"
if VRF is not configured for telent that also means telnet is disabled for that VRF so we can have only one message.
For following VRFs Telnet is enabled: A, B, C

2023-09-04 10:20 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_telnet_disabled.py
> +                        tops.actual_output["vrfs"][vrf] = "VRF is not configured."
If telnet is not configured for VRF that mean it is disabled only so its not a failure case

2023-09-06 08:17 UTC, vishwajeetgslab requested changes

2023-09-06 11:35 UTC, vishwajeetgslab requested changes

2023-09-06 11:35 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_telnet_disabled.py
> +            TS: Running `show vrf` on device and collecting the all vrfs.
```suggestion
            TS: Running `show vrf` on device and collecting all the vrfs.
```

2023-09-06 11:35 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_telnet_disabled.py
> +            # Forming output message if test result is pass
```suggestion
            # Forming output message if test result is fail
```

2023-09-06 11:35 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_telnet_disabled.py
> +                    if isinstance(vrf_data, dict):
is this needed here ?

2023-09-06 12:15 UTC, vishwajeetgslab approved these changes

2023-09-13 13:42 UTC, kgrozis-arista approved these changes

2023-09-28 20:43 UTC, merged