Issue_435:Convert Pytest-CVP L2 VLAN Name test case to Vane #435
aristanetworks/vane pull request #493
Opened 2023-08-30 09:53 UTC by rahulrajolegslab

# Please include a summary of the changes

test_definition.yaml.j2: Updated J2 with testcase NRFU5.4
master_def.yaml: Updated master def with testcase NRFU5.4
test_definition.yaml: Added test def with testcase NRFU5.4
test_security_rp_ssh_access_list.py: Added python file for testcase NRFU5.4

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on
This testcase will verify all configured VLANs have a name configured.

# Include the Issue number and link

https://github.com/aristanetworks/vane/issues/435
Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (Convert Pytest-CVP L2 VLAN Name test case to Vane)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

Unit test cases:

1. Verified that testcase pass if all configured VLANs have a name configured.
               
[report_2308301335.docx](https://github.com/aristanetworks/vane/files/12474304/report_2308301335.docx)
[report.zip](https://github.com/aristanetworks/vane/files/12474314/report.zip)

2. Verified that testcase failed if any VLANs have not a name configured.

[report_2308301455.docx](https://github.com/aristanetworks/vane/files/12474342/report_2308301455.docx)
[report.zip](https://github.com/aristanetworks/vane/files/12474345/report.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-31 07:50 UTC, vishwajeetgslab requested changes

2023-08-31 07:50 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +- name: nrfu_tests
This test case should be added to sample_network_tests/nrfu

<img width="419" alt="image" src="https://github.com/aristanetworks/vane/assets/61869155/cd6b24ab-0ab7-433b-a814-8fa37dcdf7c3">

2023-08-31 07:50 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +      description: Testcase for verification of security rp l2 vlan name functionality.
Test cases for verification of configured VLAN naming.

2023-08-31 07:50 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml.j2
> +      criteria: {{ global_dut_filter["criteria"] }}
```suggestion
      criteria: {{ global_dut_filter.criteria }}

```

2023-08-31 07:50 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_l2_vlan_name.py
> +Test cases for verification of security rp l2 vlan name functionality
```suggestion
Test cases for verification of configured VLAN naming.

```

2023-08-31 07:50 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_l2_vlan_name.py
> +class SystemHardwareFreeMemoryTests:
```suggestion
class VlanNameTests:

```

2023-08-31 07:50 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_l2_vlan_name.py
> +            vlans = output.get("vlans")
Please add a assert here to confirm that vlans are present on device. Also you can filter out dynamic vlans here itself and then only check names are present on collected VLANS.

2023-09-01 10:17 UTC, vishwajeetgslab requested changes

2023-09-01 10:17 UTC, vishwajeetgslab commented on sample_network_tests/nrfu/test_security_rp_l2_vlan_name.py
> +                            no_name_configured.append(vlan)
```suggestion
            if tops.actual_output != tops.expected_output:
                tops.output_msg = ""
                no_name_vlans = []
                for vlan, vlan_status in tops.expected_output.get("vlans").items():
                        actual_vlan_naming = (
                            tops.actual_output.get("vlans").get(vlan).get("configured_vlan_name")
                        )
                        if vlan_status["configured_vlan_name"] != actual_vlan_naming:
                            no_name_vlans.append(vlan)

```

2023-09-01 10:17 UTC, vishwajeetgslab commented on sample_network_tests/nrfu/test_security_rp_l2_vlan_name.py
> +                    f"Following VLANs are no name configured: {', '.join(no_name_configured)}."
\nFor following VLANs name is not configured:

2023-09-01 14:48 UTC, vishwajeetgslab approved these changes

2023-09-04 10:07 UTC, MaheshGSLAB requested changes

2023-09-18 09:01 UTC, MaheshGSLAB approved these changes

2023-09-27 13:23 UTC, merged