issue_425:Convert Pytest-CVP interface errors and discards test case …
aristanetworks/vane pull request #494
Opened 2023-08-30 11:21 UTC by rahulmali2512

# Please include a summary of the changes

Describe the solution you'd like
PyTest-CVP interface errors and discards test case should have the following:

Use Vane test case styling
Use Master definition file to simplify input
Add test case steps to the test case
Test should be added to top-level directory nrfu_tests
Use markers nrfu_test, interfaces
Use Test ID: NRFU2.3

# Any specific logic/part of code you need extra attention on
   From the output of  **show interfaces**,  verified that the all interfaces for errors.

# Include the Issue number and link
https://github.com/aristanetworks/vane/issues/425

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU testcases)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?
Unit testcases:

 - Tested and verified No Errors are found in all the interfaces: Passed

- Tested and verified error found for specific interface: Failed

- Tested and verified interfaces details are not found: Assert

[issue_12.zip](https://github.com/aristanetworks/vane/files/12474949/issue_12.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

- Assert reports and passed reports are generated using hardcoded output.

2023-08-31 12:02 UTC, MaheshGSLAB commented on nrfu_tests/test_interface_errors_and_discards.py
> +                if "Ethernet" in ethernets or "Management" in ethernets:
for Managment and sub interfaces we dont need to check the errors

2023-08-31 12:02 UTC, MaheshGSLAB commented on nrfu_tests/test_interface_errors_and_discards.py
> +                    runts = self.interfaces[ethernets]["interfaceCounters"]["inputErrorsDetail"][
please dont use short name in variables

2023-08-31 12:03 UTC, MaheshGSLAB commented on nrfu_tests/test_interface_errors_and_discards.py
> +                    ]["lateCollisions"]
please use the get methods for all possible places

2023-08-31 12:08 UTC, MaheshGSLAB commented on nrfu_tests/test_interface_errors_and_discards.py
> +            self.show_interfaces = self.tops.run_show_cmds([self.tops.show_cmd])
Please dont run this command again as you already mentioned the command in test def.

2023-08-31 12:16 UTC, MaheshGSLAB commented
Observation is not looks good. Please let me know once you working on this will guide you for obseravtion.
![image](https://github.com/aristanetworks/vane/assets/122076792/b1ac9cfa-1f5a-4189-bd39-a2bb6992eca2)

2023-09-01 12:01 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    description: Testcase for verification of errors on all the interfaces.
```suggestion
    description: Testcase for verification of errors/discards on all the interfaces.
```

2023-09-01 12:01 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    test_criteria: Errors should not be found on any of the interface. # Setting test case’s pass / fail criteria for reporting
```suggestion
    test_criteria: Errors/discards should not be found on any of the interface. # Setting test case’s pass / fail criteria for reporting
```

2023-09-01 12:01 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    error_threshold: 0
should be hard code in python file

2023-09-01 12:05 UTC, MaheshGSLAB commented on nrfu_tests/test_interface_errors_and_discards.py
> +                    fcs_errors = (
cant we just update the actual and expected output here only?

2023-09-01 12:11 UTC, MaheshGSLAB commented
![image](https://github.com/aristanetworks/vane/assets/122076792/c1a13b59-caee-4950-8e34-ae7207a96c5b)

Input errors
Output errors
Other errors

2023-09-01 12:13 UTC, MaheshGSLAB commented
Please dont use true/false, add the actual/expected errors count
![image](https://github.com/aristanetworks/vane/assets/122076792/29111e5c-a547-4eda-b31b-41c4acd002c6)

2023-09-04 10:36 UTC, MaheshGSLAB approved these changes

2023-09-04 15:19 UTC, vishwajeetgslab requested changes

2023-09-04 15:19 UTC, vishwajeetgslab commented on nrfu_tests/test_interface_errors_and_discards.py
> +                        continue
Add comments why these interfaces are being skipping from verification

2023-09-04 15:19 UTC, vishwajeetgslab commented on nrfu_tests/test_interface_errors_and_discards.py
> +            for ethernets in self.show_interfaces:
```suggestion
            for interface in self.show_interfaces:
```

2023-09-04 15:19 UTC, vishwajeetgslab commented on nrfu_tests/test_interface_errors_and_discards.py
> +                    self.tops.actual_output.update(
Add a variable above to avoid repeated parsing of  interface_details = self.show_interfaces.get(ethernets).get("interfaceCounters").get("inputErrorsDetail")

2023-09-04 15:19 UTC, vishwajeetgslab commented on nrfu_tests/test_interface_errors_and_discards.py
> +                                        .get("outputErrorsDetail")
Same for outputErrorDetails add a variable

2023-09-04 15:19 UTC, vishwajeetgslab commented on nrfu_tests/test_interface_errors_and_discards.py
> +                    self.tops.expected_output.update(
Can we use fromkeys method of dict here. instead of adding key and value for each error.

2023-09-04 15:19 UTC, vishwajeetgslab commented on nrfu_tests/test_interface_errors_and_discards.py
> +                    if interface_details != self.tops.actual_output.get(interface):
Variable should be added for self.tops.actual_output.get(interface)

2023-09-04 15:19 UTC, vishwajeetgslab commented on nrfu_tests/test_interface_errors_and_discards.py
> +                            f"\nFor {interface} following errors/discards are observed:\n"
```suggestion
                            f"\nFor {interface}, following non-zero errors/discards are observed:\n"
```

2023-09-06 09:36 UTC, vishwajeetgslab requested changes

2023-09-14 16:40 UTC, vishwajeetgslab approved these changes

2023-09-28 20:24 UTC, kgrozis-arista approved these changes

2023-09-28 20:24 UTC, merged