Added TC for NRFU4.4 Multi agent routing protocol functionality
aristanetworks/vane pull request #495
Opened 2023-08-30 11:31 UTC by vitthalmagadum

# Added TC for NRFU4.4 Multi agent routing protocol functionality

# Issue_ID: https://github.com/aristanetworks/vane/issues/433

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [X] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [ ] Other (please specify)

# Effort required on reviewers end

- - [X] Easy
- - [ ] Medium
- - [ ] Hard 

# Reports

Passed reports when multi agent enabled on device
[report_passed.docx](https://github.com/aristanetworks/vane/files/12475071/report_passed.docx)

Failed report when diff routing model protocol is enabled
[report_failed.docx](https://github.com/aristanetworks/vane/files/12475075/report_failed.docx)

Html Reports
[Html_reports.zip](https://github.com/aristanetworks/vane/files/12475078/Html_reports.zip)

2023-08-31 04:54 UTC, hsisalgslab commented on nrfu_tests/test_routing_multi_agent.py
> +            tops.actual_output["multi_agent_routing_protocol"]["configured"] = (
```suggestion
            tops.actual_output["multi_agent_routing_protocol"]["configured_protocol_model"] = (
```
can we update like this ?

2023-08-31 04:55 UTC, hsisalgslab commented on nrfu_tests/test_routing_multi_agent.py
> +            tops.actual_output["multi_agent_routing_protocol"]["operational"] = (
```suggestion
            tops.actual_output["multi_agent_routing_protocol"]["operational_protocol_model"] = (
```

2023-08-31 04:56 UTC, hsisalgslab commented on nrfu_tests/test_routing_multi_agent.py
> +            TS: Running 'show ip route summary' command and Verifying Multi Agent Routing Model
```suggestion
            TS: Running 'show ip route summary' command and verifying multi agent routing model protocol is configured and operational on the device.
```

2023-08-31 04:57 UTC, hsisalgslab commented on nrfu_tests/test_routing_multi_agent.py
> +            "Multi Agent Routing Model protocol is configured and operational on the device."
```suggestion
            "Multi agent routing model protocol is configured and operational on the device."
```

2023-08-31 05:10 UTC, hsisalgslab commented on nrfu_tests/test_routing_multi_agent.py
> +                    if tops.actual_output["multi_agent_routing_protocol"]["configured"]:
add unit tests for following scenarios 
1) not is in operational state
2) Routing model details are not found.
3)Multi-agent is not configured.

2023-08-31 06:57 UTC, geetanjalimanegslab requested changes

2023-08-31 06:57 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +  testcases:
Please follow the MR description format.

2023-08-31 06:57 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml.j2
> +    test_criteria: Multi Agent Routing Model protocol should be configured and operational on the device.
```suggestion
    test_criteria: Multi agent routing model protocol should be configured and operational on the device.
```

2023-08-31 06:57 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_multi_agent.py
> +from pyeapi.eapilib import EapiError
<img width="437" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/09a45a7a-029c-4d6b-89c7-0d72b51ae007">

Any reason you have mentioned dut name here?

2023-08-31 06:57 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_multi_agent.py
> +                            "Multi agent routing protocol is configured but not is in operational"
```suggestion
                            "Multi agent routing protocol is configured but it is not in the operational"
```

2023-08-31 06:57 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_multi_agent.py
> +                            "Multi agent routing protocol is neither configured nor is in"
```suggestion
                            "Multi agent routing protocol is neither configured nor in"
```

2023-08-31 13:53 UTC, geetanjalimanegslab approved these changes

2023-09-01 04:49 UTC, hsisalgslab approved these changes

2023-09-01 06:55 UTC, MaheshGSLAB requested changes

2023-09-01 06:55 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_multi_agent.py
> +    def test_routing_multi_agent(self, dut, tests_definitions):
```suggestion
    def test_multi_agent_routing_protocol(self, dut, tests_definitions):
```

2023-09-01 06:55 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_multi_agent.py
> +          dut(dict): Details related to the switches
```suggestion
          dut(dict): Details related to particular DUT
```

2023-09-01 06:55 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_multi_agent.py
> +            route_summary = dut["output"][tops.show_cmd]["text"]
just want to know can we use {'cmd':'show ip route summary', 'revision': 3} to get the json output. Did you tried if yes then want is the observation

2023-09-01 07:28 UTC, MaheshGSLAB approved these changes

2023-09-13 13:48 UTC, kgrozis-arista approved these changes

2023-09-28 20:45 UTC, merged