Added TC for NRFU5.3 LLDP neighbor functionality testcase
aristanetworks/vane pull request #498
Opened 2023-08-31 04:24 UTC by vitthalmagadum

# Added TC for NRFU5.3 LLDP neighbor functionality testcase

# Issue_ID: https://github.com/aristanetworks/vane/issues/452

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [X] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [ ] Other (please specify)

# Effort required on reviewers end

- - [X] Easy
- - [ ] Medium
- - [ ] Hard 

# Reports

Passed reports when test criteria met(no local host found in lldp details)
[report_passed.docx](https://github.com/aristanetworks/vane/files/12482181/report_passed.docx)

Failed reports when test criteria does not met.
[report_failed.docx](https://github.com/aristanetworks/vane/files/12482185/report_failed.docx)

Html reports
[Html_reports.zip](https://github.com/aristanetworks/vane/files/12482188/Html_reports.zip)

2023-09-01 07:19 UTC, MaheshGSLAB commented
I dont this we need to check any management, port-channle or sub interface
![image](https://github.com/aristanetworks/vane/assets/122076792/ebe46a33-45c4-457a-beeb-3867ee1d6bee)

2023-09-01 07:22 UTC, MaheshGSLAB commented
![image](https://github.com/aristanetworks/vane/assets/122076792/902d1ddc-d201-4cb6-911a-99e25914f138)

```
lldp_neighbor_information:
  Interfaces:
    Ethernet1:
      localhost_found: True
    Ethernet2:
      localhost_found: False
```

2023-09-01 07:23 UTC, MaheshGSLAB requested changes

2023-09-01 07:23 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml.j2
> +    test_criteria: No localhost should found in LLDP information on device.
```suggestion
    test_criteria: Localhost should not found in the LLDP neighbor information on device.
```

2023-09-01 07:23 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +            TS: Running 'show lldp neighbors detail' command and Verifying device is configured
verifying that localhost should not found on the LLDP neighbor information.

2023-09-01 07:23 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +            assert neighbor_details, f"lldp neighbor details not found on device {tops.dut_name}."
i dont know if any assert require here. We need to check as testcase says that localhost should not found in the lldp info.

2023-09-01 07:23 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +                    tops.actual_output["rp_eos_configurations"][interface] = True
we need to make more simpler keys in actual and expected output for end user. localhost_not_found: True/False

2023-09-01 07:23 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +                    f"\nOn device {tops.dut_name}, following interfaces found with localhost in"
No need to add On device in observation.

2023-09-01 07:23 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +                    f" LLDP information:\n{', '.join(localhost_found_interfaces)}"
LLDP neighbor information

2023-09-01 12:31 UTC, MaheshGSLAB requested changes

2023-09-01 12:31 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    report_style: modern   # Setting report_style as modern If report type is set to modern, then it will update steps, assumptions, and external systems in the docx report.
why there are no dut filter and criteria

2023-09-01 12:31 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +                )
```suggestion
                tops.output_msg = (
                    "\nFollowing interfaces found with localhost in"
                    f" LLDP neighbor information: {', '.join(localhost_found_interfaces)}"
                )
```

2023-09-04 04:12 UTC, vishwajeetgslab approved these changes

2023-09-04 12:34 UTC, MaheshGSLAB approved these changes

2023-09-06 20:22 UTC, rewati-arista requested changes
Some are probably nit picks with typos but to summarize changes are needed to use new logger, f-strings, refactor logic around loops and try block

2023-09-06 20:22 UTC, rewati-arista commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +        self.output = ""
same suggestion as https://github.com/aristanetworks/vane/pull/485#discussion_r1316418284

2023-09-06 20:22 UTC, rewati-arista commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +            found on the LLDP neighbor information.
typo 
```suggestion
            be found in the LLDP neighbor information.
```

2023-09-06 20:22 UTC, rewati-arista commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +            logger.info(
lets use f-string

2023-09-06 20:22 UTC, rewati-arista commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +            logger.error(
f-string

2023-09-06 20:22 UTC, rewati-arista commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +            if tops.actual_output != tops.expected_output:
from line 87-92 can be taken care of in the previous for loop itself, by initialising localhost_found_interfaces before line 60 and then adding just line 92 after line 83 within the nested if. So that way we dont have to loop through them again here

2023-09-06 20:22 UTC, rewati-arista commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +            for interface, interface_details in neighbor_details.items():
for line 60 - 96 same suggestion as https://github.com/aristanetworks/vane/pull/485/files#r1316430271

2023-09-14 08:06 UTC, vitthalmagadum commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +            if tops.actual_output != tops.expected_output:
As discussed in the call with Kevin and Shachi, they suggested keeping this change as it is.

2023-09-14 08:06 UTC, vitthalmagadum commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +            for interface, interface_details in neighbor_details.items():
As discussed in the call with Kevin and Shachi, they suggested keeping this change as it is.

2023-09-14 08:06 UTC, vitthalmagadum commented on nrfu_tests/test_security_rp_eos_no_config_test.py
> +        self.output = ""
As discussed with Kevin, not updating this change, Once the vane issue is fixed for generating a report we can remove this self. output.
Thanks,

2023-09-18 20:50 UTC, rewati-arista approved these changes
LGTM

2023-09-18 20:51 UTC, merged