Issue_423: Convert Pytest-CVP Interface Description test case to Vane #423
aristanetworks/vane pull request #499
Opened 2023-08-31 05:25 UTC by dhruvgoel9

# Please include a summary of the changes

Converted test_interfaces_description_status.py as per the vane style guide along with the updated following files.
test_definition.yaml: Updated test def with testcase NRFU2.1
test_definition.yaml.j2: Updated J2 with testcase NRFU2.1
masterdef.yaml: Added master def yaml for DUTs
nrfu_tests/test_interfaces_description_status.py: Added converted testsuite file for testcases NRFU2.1

# Any specific logic/part of code you need extra attention on

From the output of **show interfaces description**, verified that the all interface with description to verify having description and status as up, the interfaces with description to ignore having status as up, if interfaces or Vlans are not found then testcase will skip.

# Include the Issue number and link

#423 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU testcase)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?

Unit tests:

Tested the test_interfaces_description_status for all status as up and proper description where needed: Test case passed
[pass_report.docx](https://github.com/aristanetworks/vane/files/12482432/pass_report.docx)

Tested the test_interfaces_description_status for no description for description to verify: Test case failed
[fail_report_interface_not_having_description.docx](https://github.com/aristanetworks/vane/files/12482435/fail_report_interface_not_having_description.docx)

Tested the test_interfaces_description_status for down status and no description for description to verify: Test case failed
[fail_report_interface_wrong_status_no_description.docx](https://github.com/aristanetworks/vane/files/12482439/fail_report_interface_wrong_status_no_description.docx)

Tested the test_interfaces_description_status for wrong status for both the cases for description to ignore and to verify, no description for interfaces with description to verify: Test case failed
[fail_report_interfaces.docx](https://github.com/aristanetworks/vane/files/12482447/fail_report_interfaces.docx)

Tested the test_interfaces_description_status for no interface details found: Test case failed with assertion message
[assert_fail_interfaces_not_found.docx](https://github.com/aristanetworks/vane/files/12482455/assert_fail_interfaces_not_found.docx)

Tested the test_interfaces_description_status for no vlans are found: Test case failed with assertion message
[assert_fail_vlan_not_found.docx](https://github.com/aristanetworks/vane/files/12482458/assert_fail_vlan_not_found.docx)

HTML Reports:
[html_reports.zip](https://github.com/aristanetworks/vane/files/12482488/html_reports.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-31 12:43 UTC, geetanjalimanegslab requested changes

2023-08-31 12:43 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_description_status.py
> +                            " status is 'up', however actual is found as"
```suggestion
                            " status is '{expected_interface_status}', however actual is found as"
```

2023-08-31 12:43 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_description_status.py
> +                        f" description, however actual is found as none:\n{description_not_found}\n"
Updated the message as follows:
 "\nFor the following interfaces expected a description, however, it is not found:\n{description_not_found}\n"

2023-08-31 12:43 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_description_status.py
> +                            f"\nFor interface {interface}, expected status is 'up', however actual"
```suggestion
                            f"\nFor interface {interface}, expected status is '{expected_interface_status}', however actual"
```

2023-08-31 12:43 UTC, geetanjalimanegslab commented on nrfu_tests/test_interfaces_description_status.py
> +                        tops.actual_output["interfaces_description"]["descriptions_to_ignore"]
<img width="855" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/b70cf8d1-2bf1-4df4-be8e-f95d47fd18e5">

Add one line space before
For the following interfaces with

2023-09-04 10:26 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +    expected_output: null
please update the inline comment for the expected output

2023-09-04 10:36 UTC, geetanjalimanegslab approved these changes

2023-09-05 04:54 UTC, MaheshGSLAB requested changes

2023-09-05 04:54 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    test_criteria: All interfaces status should be up and interfaces should have description except the interfaces with description to ignore. # Setting test case’s pass/fail criteria for reporting
there are some global variables. Please use it in test def and master def

2023-09-05 04:54 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_description_status.py
> +        descriptions_to_ignore = ["unused", "available", "reserved", "test", "future"]
this should be define in test def and master def

2023-09-05 04:54 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_description_status.py
> +        show_cmd = ["show interfaces description", "show vlan"]
why running command from python file instead of test def

2023-09-05 04:54 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_description_status.py
> +                    tops.actual_output["interfaces_description"]["descriptions_to_ignore"].update(
there is global variable failOnNoDescription so if this true then we have to fail the testcase if no description else testcase should pass

2023-09-05 04:54 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_description_status.py
> +                if description.lower() in descriptions_to_ignore:
this is not the logic used in sample code. WE have to iterate over descriptions_to_ignore thne check any des is in description.lower()

`any(descriptionToIgnore in description.lower() for descriptionToIgnore in descriptionsToIgnore)`

2023-09-05 04:54 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_description_status.py
> +            if tops.expected_output != tops.actual_output:
please update the code for output message in case of failure. there shouldn't be more conditions as testcase fail in only two case if there is no description on interface  or interface status is down.

2023-09-05 04:54 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_description_status.py
> +                    "descriptions_to_ignore"
do not use any hardcode output to test this testcase. You can simply update the description and test it

2023-09-08 09:28 UTC, MaheshGSLAB requested changes

2023-09-08 09:28 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_description_status.py
> +            if tops.expected_output != tops.actual_output or fail_on_no_description:
suppose your actual and expected output is correct just fail_on_no_description is True in that case will be a proper output msg. I mean in that case it will just print output msg as blank

2023-09-08 09:28 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_description_status.py
> +                    tops.expected_output["interfaces"]["descriptions_not_found"].append(interface)
if fail_on_no_description is true then in case our expected output like there should be description on interface

2023-09-08 09:28 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_description_status.py
> +            if tops.expected_output != tops.actual_output or fail_on_no_description:
No output msg in case of pass
![image](https://github.com/aristanetworks/vane/assets/122076792/17b6ddba-bdc2-4f28-8966-6a40c9c7bd24)

2023-09-18 13:18 UTC, MaheshGSLAB approved these changes

2023-09-18 13:18 UTC, MaheshGSLAB commented on nrfu_tests/test_interfaces_description_status.py
> +                if interface.startswith("Vlan") and interface.lstrip("Vlan") in dynamic_vlans:
do we need the the condition  if interface.startswith("Vlan") as if interface is in dynamic vlan then we can directly continue, why is the need of checking that interface start with vlan

2023-09-20 12:22 UTC, MaheshGSLAB approved these changes

2023-09-20 20:32 UTC, rewati-arista requested changes
Suggested changes regarding: Rephrasing and commenting

2023-09-20 20:32 UTC, rewati-arista commented on nrfu_tests/test_interfaces_description_status.py
> +                # Flag to check the description is to ignore or not
```suggestion
                # Flag to check if the description is to be ignored or not
```

2023-09-20 20:32 UTC, rewati-arista commented on nrfu_tests/test_interfaces_description_status.py
> +                # Checking if the test case needs to fail or not, based on the description required
```suggestion
                # Checking if the test case needs to fail or not, based on the description requirement
```

2023-09-20 20:32 UTC, rewati-arista commented on nrfu_tests/test_interfaces_description_status.py
> +                # or not and forming output messages accordingly.
```suggestion
                # and forming output messages accordingly.
```

2023-09-20 20:32 UTC, rewati-arista commented on nrfu_tests/test_interfaces_description_status.py
> +                # Checking for the interfaces with descriptions is required or not and forming
```suggestion
                # Checking for the interfaces with descriptions requirement and forming
```

2023-09-20 20:32 UTC, rewati-arista commented on nrfu_tests/test_interfaces_description_status.py
> +                        "\nFor the following interfaces expected a description, however, it is"
```suggestion
                        "\nFor the following interfaces description was expected, however, it is"
```

2023-09-20 20:32 UTC, rewati-arista commented on nrfu_tests/test_interfaces_description_status.py
> +                if (description or fail_on_no_description) and not description_to_ignore_flag:
add a comment for this if condition (line 120), it is convoluted, same for elif on line 135

2023-09-22 18:25 UTC, rewati-arista commented on nrfu_tests/test_interfaces_description_status.py
> +        tops.actual_output = {
ah yes my bad on this

2023-09-22 18:32 UTC, rewati-arista approved these changes
LGTM

2023-09-22 18:32 UTC, merged