Issue-436:Convert Pytest-CVP Login Banner test case to Vane #436
aristanetworks/vane pull request #500
Opened 2023-08-31 06:17 UTC by paragpande24

# Please include a summary of the changes
CDescribe the solution you'd like
PyTest-CVP Login Banner test case should have the following:

Use Vane test case styling
Use Master definition file to simplify input
Add test case steps to the test case
Test should be added to top-level directory nrfu_tests
Use markers nrfu_test, security
Use Test ID: NRFU5.5

# Any specific logic/part of code you need extra attention on
 From the output of  'show banner login' and verifying that the login banner is correct.

# Include the Issue number and link
#436 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU Testcase)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?
Unit Tests:
 **Tested all the scenarios with hardcoded output.**
- Tested for all the verifying that the login banner is correct.: Passed

-[PASS_UPDATED.docx](https://github.com/aristanetworks/vane/files/12482833/PASS_UPDATED.docx)

- Tested if login banner is not enabled on switch: Failed.
 
[FAIL_UPDATED.docx](https://github.com/aristanetworks/vane/files/12482838/FAIL_UPDATED.docx)

- Tested  for verifying that the login banner is correct: Passed (With generate test definition True and J2 True )
   
[PASS_REPORT_RUNNING_ON_J2_FILE.docx](https://github.com/aristanetworks/vane/files/12482839/PASS_REPORT_RUNNING_ON_J2_FILE.docx)

HTML reports:

[Html_Reports.zip](https://github.com/aristanetworks/vane/files/12482810/Html_Reports.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-31 11:25 UTC, hsisalgslab commented on nrfu_tests/test_security_rp_login_banner.py
> +            TS: Running `show banner login` command on a DUT and verifying that the
```suggestion
            TS: Running `show banner login` command on device and verifying that the expected 

```

2023-08-31 11:27 UTC, hsisalgslab commented on nrfu_tests/test_security_rp_login_banner.py
> +                    tops.output_msg = f"Login banner is not configured on {tops.dut_name}"
```suggestion
                    tops.output_msg = f" Expected login banner is not configured on {tops.dut_name}"

```

2023-08-31 11:33 UTC, hsisalgslab commented on nrfu_tests/test_definition.yaml
> +    description: Testcase for verification of login banner is configured.
```suggestion
    description: Testcase for verification of security rp login banner
```
pls update on all applicable cases.

2023-08-31 11:35 UTC, hsisalgslab commented on nrfu_tests/master_def.yaml
> +global_dut_filter: # This stanza is optional. If it is not provided by users than all test cases should be run on each dut.
as we discussed in DSU, lets not add master def for now.

2023-08-31 11:36 UTC, hsisalgslab approved these changes

2023-09-01 09:25 UTC, hsisalgslab approved these changes

2023-09-01 11:55 UTC, vishwajeetgslab requested changes

2023-09-01 11:55 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +    description: Testcase for verification of security rp login banner.
```suggestion
    description: Testcase for verification of login banner.
```

2023-09-01 11:55 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +      login_banner_found : True
```suggestion
      login_banner_found: True
```

2023-09-01 11:55 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +    test_criteria: Expected login banner should be present on the switch. # Setting test case’s pass / fail criteria for reporting
```suggestion
    test_criteria: Login banner should be found on the device. # Setting test case’s pass / fail criteria for reporting
```

2023-09-01 11:55 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_login_banner.py
> +class SecurityRpLoginBannerTests:
```suggestion
class LoginBannerTests:

```

2023-09-01 11:55 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_login_banner.py
> +            """
```suggestion
            TS: Running `show banner login` command on device and verifying that the login banner is found on the device.
            """

```

2023-09-01 11:55 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_login_banner.py
> +                tops.actual_output = {"login_banner_found": True}
```suggestion
tops.actual_output = {"login_banner_found": bool( login_banner)}

```

2023-09-01 11:55 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_login_banner.py
> +                        f"\nExpected login banner is not configured on {tops.dut_name}."
```suggestion
                        f"\nLogin banner is not found on the device"

```

2023-09-01 11:55 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_login_banner.py
> +            output = dut["output"][tops.show_cmd]["json"]
Why command output is not added in docx report?

<img width="575" alt="image" src="https://github.com/aristanetworks/vane/assets/61869155/55653d13-2179-4a2c-a6d9-e1f0e674fe85">

2023-09-04 15:27 UTC, vishwajeetgslab requested changes

2023-09-04 15:27 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_login_banner.py
> +                    tops.output_msg = "\nLogin banner is not found on the device."
```suggestion
                    tops.output_msg = "Login banner is not found on the device."

```

2023-09-05 06:27 UTC, vishwajeetgslab approved these changes

2023-09-05 11:54 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_login_banner.py
> +        except (AssertionError, AttributeError, LookupError, EapiError) as excep:
```suggestion
        except (AttributeError, LookupError, EapiError) as excep:

```

2023-09-27 13:38 UTC, kgrozis-arista approved these changes

2023-09-27 13:38 UTC, merged