Issue_439: Convert Pytest-CVP Username No Password test case to Vane #439
aristanetworks/vane pull request #502
Opened 2023-08-31 07:57 UTC by dhruvgoel9

# Please include a summary of the changes

Converted test_security_rp_username_password.py as per the vane style guide along with the updated following files.
test_definition.yaml: Updated test def with testcase NRFU5.8
test_definition.yaml.j2: Updated J2 with testcase NRFU5.8
nrfu_tests/test_security_rp_username_password.py: Added converted testsuite file for testcases NRFU5.8

# Any specific logic/part of code you need extra attention on

From the output of show running-config all section ^username, verified that the all username configured with a password , if usernames are not found then testcase will skip.

# Include the Issue number and link

#439 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU test case)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?

Unit tests:

Tested test_security_rp_username_password with username have password configured: Test case passed
[pass_report.docx](https://github.com/aristanetworks/vane/files/12483879/pass_report.docx)

Tested test_security_rp_username_password with username are not configured with password: Test case failed
[fail_report_no_password.docx](https://github.com/aristanetworks/vane/files/12483883/fail_report_no_password.docx)

Tested test_security_rp_username_password with usernames are not found: Test case failed with assertion message
[assert_fail.docx](https://github.com/aristanetworks/vane/files/12483886/assert_fail.docx)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-31 11:38 UTC, hsisalgslab commented on nrfu_tests/test_security_rp_username_password.py
> +# Copyright (c) 2023 Arista Networks, Inc.  All rights reserved.
add label enhancement

2023-08-31 11:41 UTC, hsisalgslab commented on nrfu_tests/test_definition.yaml.j2
> +      criteria: {{ global_dut_filter["criteria"] }}
```suggestion
      criteria: {{ global_dut_filter.criteria }}
```
access like this

2023-08-31 11:42 UTC, hsisalgslab commented on nrfu_tests/test_security_rp_username_password.py
> +class SecurityRPUsernamePasswordTests:
```suggestion
class SecurityRPUsernameNoPasswordTests:
```
can we update like this ?

2023-08-31 11:42 UTC, hsisalgslab commented on nrfu_tests/test_security_rp_username_password.py
> +        TD: Test case for verification of username password status.
```suggestion
        TD: Test case for verification of username and password status.
```
check for applicable cases

2023-09-01 11:43 UTC, dhruvgoel9 commented on nrfu_tests/test_security_rp_username_password.py
> +# Copyright (c) 2023 Arista Networks, Inc.  All rights reserved.
enhancement label is not required

2023-09-04 08:43 UTC, dhruvgoel9 commented on nrfu_tests/test_security_rp_username_password.py
> +class SecurityRPUsernamePasswordTests:
class name is updated as per discussion with vishwajeet

2023-09-04 08:56 UTC, hsisalgslab approved these changes

2023-09-04 15:47 UTC, vishwajeetgslab requested changes

2023-09-04 15:47 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +    description: Test cases for verification of password configuration for user.
```suggestion
    description: Test cases for verification of password configuration for user accounts.
```

2023-09-04 15:47 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml.j2
> +  {% set master_data = testcase_data %}
is this required here ?

2023-09-04 15:47 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_username_password.py
> +        tops.output_msg = "All usernames are configured with a password."
```suggestion
        tops.output_msg = "All user accounts are configured with a password."
```

2023-09-04 15:47 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +    test_criteria: All usernames should be configured with a password. # Setting test case’s pass/fail criteria for reporting
```suggestion
    test_criteria: All user accounts should be configured with a password. # Setting test case’s pass/fail criteria for reporting
```

2023-09-04 15:47 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_username_password.py
> +        TD: Test cases for verification of password configuration for user.
Update as per comment on test def. Applicable at all other places.

2023-09-04 15:47 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_username_password.py
> +            assert output, "Username details are not found in the output."
```suggestion
            assert output, "User account details are not found in the output."
```

2023-09-04 15:47 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_username_password.py
> +                    tops.expected_output.update({username: {"username_password_found": True}})
```suggestion
                    tops.expected_output.update({username: {"password_configured": True}})
```

2023-09-04 15:47 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_username_password.py
> +                        tops.actual_output.update({username: {"username_password_found": True}})
```suggestion
                    tops.actual_output.update({username: {"username_password_found": True}})
                    if password == "nopassword":
                        tops.actual_output.update({username: {"username_password_found": False}})
```

2023-09-04 15:47 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_username_password.py
> +                        f" password:\n{', '.join(password_not_configured)}"
```suggestion
                        "Following user accounts are not configured with a"
                        f" password:{', '.join(password_not_configured)}"
```

2023-09-06 10:22 UTC, vishwajeetgslab requested changes

2023-09-06 10:22 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +      description: Test cases for verification of password configuration for user accounts.
```suggestion
      description: Test case for verification of password configuration for user accounts.
```

2023-09-06 10:22 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_username_password.py
> +Test cases for verification of password configuration for user accounts.
```suggestion
Test case for verification of password configuration for user accounts.
```

2023-09-06 10:22 UTC, vishwajeetgslab commented on nrfu_tests/test_security_rp_username_password.py
> +                        f" password:\n{', '.join(password_not_configured)}"
```suggestion
                        f" password: {', '.join(password_not_configured)}"
```

2023-09-18 06:42 UTC, vishwajeetgslab approved these changes

2023-09-29 14:48 UTC, kgrozis-arista approved these changes

2023-09-29 14:48 UTC, merged