Added TC for NRFU4.3 EVPN L2 VNI routes details verification
aristanetworks/vane pull request #504
Opened 2023-08-31 10:39 UTC by vitthalmagadum

# Please include a summary of the changes

test_definition.yaml: Updated test def with testcase NRFU4.3
test_definition.yaml.j2: Updated J2 with testcase NRFU4.3
master_def.yaml: Updated master def file for NRFU4.3
test_routing_evpn_l2vni_imet.py: Added python file for testcase NRFU4.3

# Any specific logic/part of code you need extra attention on

Running `show bgp evpn summary` command and verifying EVPN is configured on the device also
Running `show interfaces <vxlan interface>` command and verifying L2 VNIs are configured on the device

# Issue_ID: https://github.com/aristanetworks/vane/issues/432

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [X] Other (NRFU Tests)

# Effort required on reviewers end

- - [ ] Easy
- - [X] Medium
- - [ ] Hard 

# Reports

Passed reports when EVPN routes are advertised for all VNIs
[report_passed.docx](https://github.com/aristanetworks/vane/files/12485223/report_passed.docx)

Failed reports when test criteria does not met
[report_failed.docx](https://github.com/aristanetworks/vane/files/12485226/report_failed.docx)

Skipped reports when ribd model protocol is enabled. EVPN is not configured
[report_skipped.docx](https://github.com/aristanetworks/vane/files/12485231/report_skipped.docx)

Failed assert report when command output not found.
[report_assert_failed.docx](https://github.com/aristanetworks/vane/files/12485237/report_assert_failed.docx)

Html Reports
[Html_reports.zip](https://github.com/aristanetworks/vane/files/12485244/Html_reports.zip)

2023-09-01 10:59 UTC, geetanjalimanegslab requested changes

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +      vxlan_interface: Vxlan1
the filter and criteria details also needed right? as you have mentioned the global dut.

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                assert bgp_evpn_peer, "No established EVPN peer found."
```suggestion
                assert bgp_evpn_peer, "BGP even peers state is not Established ."
```

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                    "On device %s, Output of %s command is:\n%s\n",
<img width="387" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/ab643760-8fe8-4389-8c65-0140a39019b2">

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                assert vxlan_details, "No vlan to VNI mapping found in vxlan command details."
```suggestion
                assert vxlan_details, "VLAN to VNI mapping is not found in vxlan command details."
```

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                show_vxlan_command = f"show interfaces {vxlan_interface}"
can we use nested try block for this command 
<img width="606" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/c7392f2b-4794-49ab-bb12-eb885dbfef9c">

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                        advertised_route_details = tops.run_show_cmds([route_show_command])
same for this command as well, please confirm with Mahesh once, do we need to use the nested try block here?

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                            f" {show_vxlan_command} is:\n{advertised_route_details}\n"
please confirm the self.output

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                tops.show_cmd,
<img width="558" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/f485c1eb-9756-4eb1-b07f-7ec15c5405ee">

tops.show_cmd is not defined here

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                f"On device {tops.dut_name}, Output of {tops.show_cmd} is:\n{evpn_summary}\n"
same as above

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                        if not tops.actual_output["vrfs"][vrf]["virtual_network_identifiers"][vni][
can we have a variable for tops.actual_output["vrfs"][vrf]["virtual_network_identifiers"]

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                    if not vxlan_details[vlan].get("source"):
what if the vlan source details are found for all the vlans? is it a valid case? Please correct me if I am wrong

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                            f" advertised:\n{', '.join(no_imet_routes_advertised)}\n"
```suggestion
                            f" advertised: {', '.join(no_imet_routes_advertised)}\n"
```

2023-09-01 10:59 UTC, geetanjalimanegslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +
If any Unit test requires hardcoded output, please mention the same in unit test section of MR

2023-09-05 07:19 UTC, MaheshGSLAB requested changes

2023-09-05 07:19 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +            if skip_on_command_unavailable_check:
please follow the same condition as mention is sample code
![image](https://github.com/aristanetworks/vane/assets/122076792/97d20bf7-6869-4d60-902f-d1093d3899c6)

2023-09-05 07:19 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +            assert vrf_details, "VRF details are not found in EVPN bgp route summary."
default VRF will always there so i dont think this assert we need here

2023-09-05 07:19 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +            assert evpn_running, "EVPN is not configured on the device."
If EVPN is not configured then in sample code not mentioned that we have to fail the testcase. I think we need to skip the testcase for that case
![image](https://github.com/aristanetworks/vane/assets/122076792/59f86a52-f939-4f7e-b112-f7b5e4925631)

2023-09-05 07:19 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                        route-type imet vni <vni>` command and verifying EVPN is configured
verifying VNI is advertising imet out

2023-09-05 07:19 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                for vrf in tops.actual_output["vrfs"]:
can we have the observation for multiple VRFs
![image](https://github.com/aristanetworks/vane/assets/122076792/4b1e30e4-04f2-47d3-bb55-ec6cad45c501)

2023-09-05 07:19 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                        "Command unavailable, device might be in ribd mode. hence test skipped."
which command please mention it so will be easy for end user
![image](https://github.com/aristanetworks/vane/assets/122076792/b78f8f5e-9ea7-458c-80c3-0e0af61fcdc2)

2023-09-05 07:19 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                pytest.skip("Vxlan interface does not exist / no L2 VNIs.")
which vxlan interface please mention it
![image](https://github.com/aristanetworks/vane/assets/122076792/44e19093-6bfc-4280-8389-ded1f8c4eff5)

2023-09-06 08:18 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +            if skip_on_command_unavailable_check:
suppose there is Lookup error or Attribute error and flag is set true for skip in that case also testcase will skip. Please add the condition of eapi error and skip flag then only testcase should skip

2023-09-06 08:22 UTC, MaheshGSLAB commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                pytest.skip("EVPN is not configured on the device.")
![image](https://github.com/aristanetworks/vane/assets/122076792/90fef2ee-5b6c-4112-a56c-eef6ea694cba)

2023-09-14 12:09 UTC, MaheshGSLAB approved these changes

2023-09-14 17:02 UTC, geetanjalimanegslab approved these changes

2023-09-29 14:28 UTC, kgrozis-arista approved these changes

2023-09-29 14:29 UTC, merged