issue_429: Converted Pytest-CVP misc show test case to Vane #429
aristanetworks/vane pull request #505
Opened 2023-08-31 11:05 UTC by hsisalgslab

# Please include a summary of the changes

Converted test_misc_show_commands.py as per the vane style guide along with that updated following files.
test_definition.yaml: Updated test def with testcase NRFU3.1
test_definition.yaml.j2 : Updated J2 with testcase NRFU3.1

# Any specific logic/part of code you need extra attention on

Verified misc show commands are ran successfully on the device.

# Include the Issue number and link
https://github.com/aristanetworks/vane/issues/429

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (nrfu test development)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?
**Note: Tested with one more show comma**
Unit tests and report :

1) Pass_case : Verified that  misc show commands are ran successfully on the device.

[pass_report_misc_show_cmds.docx](https://github.com/aristanetworks/vane/files/12485397/pass_report_misc_show_cmds.docx)

2) Fail_case : Verified that test case throws exception when  show commands are not ran successfully on the device.
Reports:

[unavailable_command.docx](https://github.com/aristanetworks/vane/files/12485400/unavailable_command.docx)

3) Fail_case : Verified that test case throws exception when one ore more show commands are not ran successfully on the device.
Reports:

[one_or_more_unavilable_command.docx](https://github.com/aristanetworks/vane/files/12485411/one_or_more_unavilable_command.docx)

HTML reports for all mentioned unit testcases:

[misc_show_commands_html_report.zip](https://github.com/aristanetworks/vane/files/12485433/misc_show_commands_html_report.zip)

## Bug fix

    
## New feature
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    
# Additional comments

2023-09-01 07:32 UTC, vishwajeetgslab requested changes

2023-09-01 07:32 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +    test_criteria: Show commands should be ran successfully on the device.
```suggestion
    test_criteria: Show commands should be executed successfully on the device.
```

2023-09-01 07:32 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml.j2
> +      test_criteria: Show commands should be written to config directory. # Setting test case’s pass / fail criteria for reporting
```suggestion
      test_criteria: Show commands should be executed on device without any error. # Setting test case’s pass / fail criteria for reporting
```

2023-09-01 07:32 UTC, vishwajeetgslab commented on nrfu_tests/test_misc_show_commands.py
> +            """
```suggestion
            """
            TS: Running show commands on device and verifying show commands are executed successfully
            on the device.
            """
```

2023-09-01 07:32 UTC, vishwajeetgslab commented on nrfu_tests/test_misc_show_commands.py
> +                    tops.expected_output["misc_show_commands"].update(
```suggestion
                    tops.expected_output["show_commands"].update(
```

2023-09-01 07:32 UTC, vishwajeetgslab commented on nrfu_tests/test_misc_show_commands.py
> +                        tops.actual_output["misc_show_commands"].update(
If any other error than unavailable command can we handle that as well here

2023-09-01 11:33 UTC, vishwajeetgslab approved these changes

2023-09-04 09:28 UTC, MaheshGSLAB requested changes

2023-09-04 09:28 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml.j2
> +      show_cmd: null # Forming show command in test case file.
comments in J2 should above to line

2023-09-04 09:28 UTC, MaheshGSLAB commented on nrfu_tests/test_misc_show_commands.py
> +                            "\nCommand execution on device is failed with following"
![image](https://github.com/aristanetworks/vane/assets/122076792/f5ec8cf0-2b4d-487b-9637-1dd3f11736c4)

In first we mention which show command but in second case not mentioning the show command so it show be similar for both case. Also are we sure all Unavailable command are hardware dependent only?

2023-09-04 11:40 UTC, hsisalgslab commented on nrfu_tests/test_misc_show_commands.py
> +                            "\nCommand execution on device is failed with following"
1. -updated show command in second case
2.  confirmed with @vishwajeetgslab

2023-09-05 05:49 UTC, MaheshGSLAB requested changes

2023-09-05 05:49 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    - BLFE1
please correct the format as suggested

2023-09-05 12:24 UTC, MaheshGSLAB requested changes

2023-09-05 12:24 UTC, MaheshGSLAB commented on nrfu_tests/test_misc_show_commands.py
> +# Copyright (c) 2023 Arista Networks, Inc.  All rights reserved.
pipeline is failed please check

2023-09-08 09:47 UTC, MaheshGSLAB requested changes

2023-09-08 09:47 UTC, MaheshGSLAB commented on nrfu_tests/test_misc_show_commands.py
> +from vane.logger import logger
do the logger change and Grammarly if not done

2023-09-14 04:34 UTC, MaheshGSLAB requested changes

2023-09-14 04:34 UTC, MaheshGSLAB commented on nrfu_tests/test_misc_show_commands.py
> +# Arista Networks, Inc. Confidential and Proprietary.
the copyright is not proper please add full copyright

2023-09-14 07:06 UTC, MaheshGSLAB approved these changes

2023-09-27 13:46 UTC, kgrozis-arista approved these changes

2023-09-27 13:46 UTC, merged