Issue-447: Testcase for Convert Pytest-CVP Inventory test case to Vane
aristanetworks/vane pull request #506
Opened 2023-08-31 11:10 UTC by AbhijeetGSLAB

# Please include a summary of the changes
Converted the testcase as per the vane styling guide with the following changes in the below files:
*  test_definition.yaml: Updated test definition with testcase contents
* test_definition.yaml.j2: Updated the J2 file with the testcase steps
* test_system_hardware_inventory.py: Added the testcase file for inventory testcase.

# Any specific logic/part of code you need extra attention on
From the output of the show command, verified that the card slots are inserted and present on the devices.

Explain any specific logic you need special attention on

# Include the Issue number and link
#447 
Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU Testcase)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?
Unit Test Cases:
Note: Tested the testcase using the hardcoded output as the command does not give required output on ACT and Tier Point Lab.

1. Tested the testcase for pass scenario where all the cards are inserted and present on the device.

- [Pass Reports.zip](https://github.com/aristanetworks/vane/files/12485437/Pass.Reports.zip)

2. Tested the testcase for fail scenario where some cards are not inserted on the device

- [Fail Reports.zip](https://github.com/aristanetworks/vane/files/12485447/Fail.Reports.zip)

3. Tested the testcase for pass scenario using J2 File

- [Pass using J2.zip](https://github.com/aristanetworks/vane/files/12485450/Pass.using.J2.zip)

4. Tested the testcase for fail scenario using J2 File

- [Fail using J2.zip](https://github.com/aristanetworks/vane/files/12485456/Fail.using.J2.zip)

5. Tested the testcase for the scenario where testcase is skipped if the device is vEOS

- [Skipped.zip](https://github.com/aristanetworks/vane/files/12485465/Skipped.zip)

6. Tested the testcase for assertion scenario where fan Tray slot is not present on the device.

- [Assertion fan trays.zip](https://github.com/aristanetworks/vane/files/12485476/Assertion.fan.trays.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-31 12:37 UTC, vishwajeetgslab requested changes

2023-08-31 12:37 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_inventory.py
> +
Avoid using multiple conditions here

2023-08-31 12:37 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +    test_criteria: Power supply, fan tray and other card slots should be inserted and present on the device. # Setting test case’s pass/fail criteria for reporting
```suggestion
    test_criteria: Power supply, fan tray and other card slots should be installed on the device. # Setting test case’s pass/fail criteria for reporting
```

2023-08-31 12:37 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +    hardware_inventory_verification_check: # Change to True or False based on if you want to fail if a particular module type is missing.
```suggestion
    hardware_inventory_checks: # Change to True or False based on if you want to fail if a particular module type is missing.
```

2023-08-31 12:37 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_inventory.py
> +            if test_params["hardware_inventory_verification_check"]["missing_fan_tray_check"]:
We can avoid these if conditions by collecting required key from test definitions verification checks

2023-09-05 07:51 UTC, vishwajeetgslab requested changes

2023-09-05 07:51 UTC, vishwajeetgslab commented on nrfu_tests/master_def.yaml
> +      missing_fanTraySlots_check: True
```suggestion
      fail_on_missing_fan_tray_slots: True
```

2023-09-05 07:51 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_inventory.py
> +            for slot, verify_slot in test_params["hardware_inventory_checks"].items():
This loop can be avoided with if else condition in 1st loop.

2023-09-06 11:14 UTC, vishwajeetgslab approved these changes

2023-09-06 12:32 UTC, MaheshGSLAB requested changes

2023-09-06 12:32 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +- name: nrfu_tests
resolve the conflicts

2023-09-06 12:32 UTC, MaheshGSLAB commented on nrfu_tests/master_def.yaml
> +      fail_on_missing_linecard_card_slots: True
```suggestion
      fail_on_missing_linecard_card_slots: False
```

2023-09-06 12:32 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml.j2
> +      hardware_inventory_checks:
just access whole dict, why you are defining keys and just accessing values

2023-09-06 12:32 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_inventory.py
> +class SystemHardwareInventoryTests:
```suggestion
class HardwareInventoryTests:
```

2023-09-06 12:32 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_inventory.py
> +                tops.output_msg = "\nThe following card slots are not inserted:"
Pass report should be from hardware device not vEOS
![image](https://github.com/aristanetworks/vane/assets/122076792/004f5200-f856-4785-94da-a764a3d2bcb9)

2023-09-06 12:32 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_inventory.py
> +                        message = f"\n{slot_name.replace('_', ' ')}: "
Line gap is not required
![image](https://github.com/aristanetworks/vane/assets/122076792/cd6a4dbd-e76b-42d6-b2e9-c01ac6a571ae)

2023-09-06 12:32 UTC, MaheshGSLAB commented on nrfu_tests/master_def.yaml
> +      fail_on_missing_fan_tray_slots: True
what if all flag set to false. Add the report for the same

2023-09-08 09:49 UTC, MaheshGSLAB requested changes

2023-09-08 09:49 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_inventory.py
> +from vane.logger import logger
Update the logger and check for Grammarly

2023-09-11 09:59 UTC, MaheshGSLAB approved these changes

2023-09-19 23:52 UTC, rewati-arista requested changes

2023-09-19 23:52 UTC, rewati-arista commented on nrfu_tests/test_system_hardware_inventory.py
> +            for slot, verify_slot in test_params["hardware_inventory_checks"].items():
Can we add comments for section from 81-124 for better understanding of what is being tested, the code gets a bit convoluted so comments would be helpful. At least a comment distinguishing the if and else block within the bigger if, because the difference is not very apparent via the logic. 😅

2023-09-20 17:30 UTC, AbhijeetGSLAB commented on nrfu_tests/test_system_hardware_inventory.py
> +            for slot, verify_slot in test_params["hardware_inventory_checks"].items():
Updated the inline comments in the MR. Also resolved the conflicts and tested the testcase after the conflicts resolution. Thanks

2023-09-20 20:20 UTC, rewati-arista approved these changes
LGTM

2023-09-20 20:20 UTC, merged