issue_440: Convert Pytest-CVP Bad SysLog test case to Vane
aristanetworks/vane pull request #507
Opened 2023-08-31 12:33 UTC by rahulmali2512

# Please include a summary of the changes

Describe the solution you'd like
PyTest-CVP Bad SysLog test case should have the following:

Use Vane test case styling
Use Master definition file to simplify input
Add test case steps to the test case
Test case should be skipped if SysLog is not configured
Test should be added to top-level directory nrfu_tests
Use markers nrfu_test, system
Use Test ID: NRFU6.1

# Any specific logic/part of code you need extra attention on
   From the output of  **show logging last <daysOfLogs> days**,  verified the key words in syslog events that are generally considered to be bad

# Include the Issue number and link
https://github.com/aristanetworks/vane/issues/440

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU testcases)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?
Unit testcases:

 - Tested and verified no bad syslog messages are found: Passed
[report_pass_with_test_def_1.docx](https://github.com/aristanetworks/vane/files/12684307/report_pass_with_test_def_1.docx)
[report_pass_with_j2.docx](https://github.com/aristanetworks/vane/files/12684315/report_pass_with_j2.docx)

- Tested and verified bad syslog messages are found: Failed
[report_fail_1.docx](https://github.com/aristanetworks/vane/files/12684322/report_fail_1.docx)

- Tested and verified logging details are not found.: Assert
[report_Assert_1.docx](https://github.com/aristanetworks/vane/files/12684324/report_Assert_1.docx)

- Tested and verified syslog is not configured: Skipped
[report_Skipped_1.docx](https://github.com/aristanetworks/vane/files/12684338/report_Skipped_1.docx)

- html Reports
[issue_30_html_reports.zip](https://github.com/aristanetworks/vane/files/12684347/issue_30_html_reports.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

- Assert reports are generated using hardcoded output.

2023-08-31 15:46 UTC, hsisalgslab commented on nrfu_tests/master_def.yaml
> +global_dut_filter: # This stanza is optional. If it is not provided by users than all test cases should be run on each dut.
as discussed in DSU, lets not add master def for now

2023-08-31 15:49 UTC, hsisalgslab commented on nrfu_tests/test_definition.yaml
> +    days_of_logs: 7
can we confirm ? this can be taken from master_def.yaml

2023-08-31 15:56 UTC, hsisalgslab commented on nrfu_tests/test_bad_syslog_events.py
> +            tops.expected_output.update({"bad_syslog_event_found": False})
![image](https://github.com/aristanetworks/vane/assets/122077912/e12e19ff-7152-4c07-bbef-fc7a6b9c627a)
it should be bad_syslog_event_found: true 
discuss if you have any confusion on this

2023-08-31 15:59 UTC, hsisalgslab commented on nrfu_tests/test_definition.yaml
> +  - name: test_bad_syslog_events
```suggestion
  - name: test_system_hardware_bad_syslog_event
```
can we update update function like this ?

same for .py file name

2023-08-31 16:02 UTC, hsisalgslab commented on nrfu_tests/test_bad_syslog_events.py
> +            tops.actual_output.update({"bad_syslog_event_found": len(bad_syslog) > 0})
```suggestion
            tops.actual_output.update({"bad_syslog_events_found": len(bad_syslog) > 0})
```

2023-08-31 16:05 UTC, hsisalgslab commented on nrfu_tests/test_bad_syslog_events.py
> +            tops.expected_output.update({"bad_syslog_event_found": False})
![image](https://github.com/aristanetworks/vane/assets/122077912/de508cc2-5da5-4526-91b1-4c62fd1162e7)

can we form this starting of the test case so  ?

2023-09-01 10:54 UTC, hsisalgslab approved these changes

2023-09-01 13:07 UTC, vishwajeetgslab requested changes

2023-09-04 15:29 UTC, vishwajeetgslab commented on nrfu_tests/master_def.yaml
> +    days_of_logs: 7
Add inline comment

2023-09-04 15:29 UTC, vishwajeetgslab commented on nrfu_tests/test_bad_syslog_events.py
> +Test cases for verification of bad syslog events messages
```suggestion
Test cases for verification of bad syslog event messages
```

2023-09-04 15:31 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml
> +  - name: test_bad_syslog_events
format properly.

2023-09-04 15:32 UTC, vishwajeetgslab commented on nrfu_tests/test_definition.yaml.j2
> +      {% set log_data = master_data["NRFU6.1"] %}
No need to add these two variables. you can directed add testcase_data["NRFU6.1"] in front of days_of_logs

2023-09-04 15:34 UTC, vishwajeetgslab commented on nrfu_tests/test_bad_syslog_events.py
> +                    f"Following bad syslog events are found on the device: \n{bad_syslog}"
```suggestion
                    f"\nFollowing bad syslog events are found on the device: \n{bad_syslog}"
```

2023-09-07 12:17 UTC, vishwajeetgslab requested changes

2023-09-07 12:17 UTC, vishwajeetgslab commented on nrfu_tests/master_def.yaml
> +global_dut_filter: # This stanza is optional. If it is not provided by users than all test cases should be run on each dut.
Why we are changing this

2023-09-14 15:58 UTC, vishwajeetgslab approved these changes

2023-09-28 20:29 UTC, kgrozis-arista approved these changes

2023-09-28 20:30 UTC, merged