Issue-441:Convert Pytest-CVP Cooling Status test case to Vane #441
aristanetworks/vane pull request #508
Opened 2023-08-31 13:50 UTC by paragpande24

# Please include a summary of the changes
Describe the solution you'd like
PyTest-CVP Cooling Status test case should have the following:

Use Vane test case styling
Use Master definition file to simplify input
Add test case steps to the test case
Test case should be skipped if vEOS
Test should be added to top-level directory nrfu_tests
Use markers nrfu_test, system
Use Test ID: NRFU6.2

# Any specific logic/part of code you need extra attention on

 From the output of  'show version' command for Skipping test case and `show system environment cooling` command 
  for system status is ok.

# Include the Issue number and link
#441 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU Testcase)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?
Unit Tests:
 **Tested all the scenarios with hardcoded output.**

- Tested for all the verifying that the system status is ok..: Passed

[PASS_REPORT.docx](https://github.com/aristanetworks/vane/files/12486740/PASS_REPORT.docx)

- Tested if system status is not ok.: Failed.
 
[FAIL_REPORT.docx](https://github.com/aristanetworks/vane/files/12486751/FAIL_REPORT.docx)

- Tested  for verifying that the system status is ok.: Passed (With generate test definition True and J2 True )

[PASS_WITH_J2_FILE_TRUE.docx](https://github.com/aristanetworks/vane/files/12486759/PASS_WITH_J2_FILE_TRUE.docx)

   
Tested  for verifying Skipping the test case for device if platform is vEOS.

[SKIP_REPORT.docx](https://github.com/aristanetworks/vane/files/12486761/SKIP_REPORT.docx)

HTML reports:

[All_HTML_REPORTS.zip](https://github.com/aristanetworks/vane/files/12486734/All_HTML_REPORTS.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-08-31 16:17 UTC, hsisalgslab commented on nrfu_tests/test_system_hardware_cooling_status.py
> +        tops.output_msg = "System cooling status is ok."
```suggestion
        tops.output_msg = "System cooling status is ok."

```

2023-08-31 16:17 UTC, hsisalgslab commented on nrfu_tests/test_definition.yaml
> +    test_criteria: System cooling status should be ok. # Setting test case’s pass / fail criteria for reporting
```suggestion
    test_criteria: System cooling status should be ok with expected ambient temperature. # Setting test case’s pass / fail criteria for reporting
```

2023-08-31 16:18 UTC, hsisalgslab commented on nrfu_tests/test_system_hardware_cooling_status.py
> +        tops.output_msg = "System cooling status is ok."
as per comment in test def

2023-08-31 16:18 UTC, hsisalgslab commented on nrfu_tests/test_system_hardware_cooling_status.py
> +            TS: Running 'show version' command on device and Skipping the test case
```suggestion
            TS: Running `show version` command on device and skipping the test case

```

2023-08-31 16:18 UTC, hsisalgslab commented on nrfu_tests/test_system_hardware_cooling_status.py
> +            self.output += f"\n\nOutput of 'show version' command is: \n{version_output}"
```suggestion
            self.output += f"Output of 'show version' command is: \n{version_output}"

```

2023-08-31 16:19 UTC, hsisalgslab commented on nrfu_tests/test_system_hardware_cooling_status.py
> +            tops.expected_output.update({"system_cooling_status": "coolingOk"})
can we form this in starting of the test case ?

2023-08-31 16:22 UTC, hsisalgslab commented on nrfu_tests/test_system_hardware_cooling_status.py
> +                pytest.skip(f"{tops.dut_name} is vEOS device, hence test skipped.")
```suggestion
                pytest.skip(f"{tops.dut_name} is vEOS device, hence test is skipped.")

```

2023-09-01 05:39 UTC, hsisalgslab approved these changes

2023-09-01 11:21 UTC, geetanjalimanegslab requested changes

2023-09-01 11:21 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +    expected_output: null # Forming expected output in test file.
please update the following block with 
<img width="460" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/b3c68139-7bb8-4215-8674-8b0b0fb32ac0">

similar to this 
<img width="602" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/a4b3a22e-5dbc-43fa-a65e-3e8cb97e74df">

2023-09-01 11:21 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +      - BLFE1
<img width="592" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/52906624-adea-49b6-a74a-d5991688e48f">

Please update this block with what exactly this test case is all about and the verification parameters.

2023-09-01 11:21 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml.j2
> +      description: Testcase for verification system cooling status.
```suggestion
      description: Testcase for the verification of system cooling status.

```

2023-09-01 11:21 UTC, geetanjalimanegslab commented on nrfu_tests/test_definition.yaml
> +    description: Testcase for verification system cooling status.
```suggestion
    description:  Testcase for the verification of system cooling status.
```

2023-09-01 11:21 UTC, geetanjalimanegslab commented on nrfu_tests/test_system_hardware_cooling_status.py
> +Testcase for verification system cooling status.
Testcase for the verification of system cooling status.

2023-09-01 11:21 UTC, geetanjalimanegslab commented on nrfu_tests/test_system_hardware_cooling_status.py
> +        TD: Testcase for verification system cooling status.
same as above

2023-09-01 11:21 UTC, geetanjalimanegslab commented on nrfu_tests/test_system_hardware_cooling_status.py
> +                    f" is: {ambient_temperature} C"
please use the following format for ambient temperature

<img width="402" alt="image" src="https://github.com/aristanetworks/vane/assets/96573243/f6b8fc83-b5e6-4cdd-8618-4a65892b9535">

2023-09-01 11:21 UTC, geetanjalimanegslab commented on nrfu_tests/test_system_hardware_cooling_status.py
> +                    "System cooling status is not ok.\nAmbient Temperature"
```suggestion
                    "System cooling status is not ok. Ambient Temperature"

```

2023-09-05 05:58 UTC, MaheshGSLAB requested changes

2023-09-05 05:58 UTC, MaheshGSLAB commented on nrfu_tests/test_definition.yaml
> +    test_criteria: System cooling status should be 'coolingOk' with expected ambient temperature. # Setting test case’s pass / fail criteria for reporting
we are not going to verify the temp. Just the status should not coolingOk. If not ok then in observation we should print the temp

2023-09-05 05:58 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_cooling_status.py
> +class SystemHardwareCoolingStatusTests:
```suggestion
class SystemCoolingStatusTests:

```

2023-09-05 05:58 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_cooling_status.py
> +        tops.expected_output = {"system_cooling_status": "coolingOk"}
put it in test def. There is no dynamic param then why its in python file

2023-09-05 05:58 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_cooling_status.py
> +                    f"{format(ambient_temperature,'.2f')}C')"
![image](https://github.com/aristanetworks/vane/assets/122076792/aa07af87-2396-4a06-b1a6-bfb6d55177b2)
 Please remove this extra closing parenthesis

2023-09-05 12:27 UTC, MaheshGSLAB approved these changes

2023-09-06 08:07 UTC, geetanjalimanegslab approved these changes

2023-09-28 20:37 UTC, kgrozis-arista approved these changes

2023-09-28 20:46 UTC, merged