issue-434:Convert Pytest-CVP API access test case to Vane
aristanetworks/vane pull request #512
Opened 2023-09-01 07:04 UTC by rohitsinghgslab

# Please include a summary of the changes

Convert Pytest-CVP API access test case to Vane as per the vane style guide along with that updated following files.
test_definition.yaml: Updated test def with testcase NRFU5.1
test_definition.yaml.j2  : Updated J2 with testcase NRFU5.1

# Any specific logic/part of code you need extra attention on

Verified  power supplies fan status.

# Include the Issue number and link
#434 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (please specify)

# Effort required on reviewers end

- - [ ] Easy
- - [x] Medium
- - [ ] Hard 

# How Has This Been Tested?
**Note: Tested with using hardcoded output**
Unit tests and report :
**Reports:**
Pass case:All VRFs that the API is active are ACL configured.
[report_2309011202.docx](https://github.com/aristanetworks/vane/files/12495251/report_2309011202.docx)

Fail case: All VRFs that the API is active are not ACL configured.
[report_2309011206.docx](https://github.com/aristanetworks/vane/files/12495261/report_2309011206.docx)

Assert VRFs: Vrfs details are not found in output.
[report_2309011204.docx](https://github.com/aristanetworks/vane/files/12495266/report_2309011204.docx)

Assert ACLs: ACL details for APIs is not found in output.
[report_2309011205.docx](https://github.com/aristanetworks/vane/files/12495269/report_2309011205.docx)

HTML Reports:
[PC_434_HTML.zip](https://github.com/aristanetworks/vane/files/12495291/PC_434_HTML.zip)

## Bug fix

    
## New feature
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    
# Additional comments

2023-09-05 07:12 UTC, AbhijeetGSLAB commented on nrfu_tests/test_acls_api_access_list.py
> +Testcase for verification of ACLs are applied to each VRF the API is enabled on.
Change the file name to test_security_rp_api_access_list.py

2023-09-05 07:51 UTC, AbhijeetGSLAB commented on nrfu_tests/test_acls_api_access_list.py
> +                    actual_vrf_status = tops.actual_output["vrf_details"].get(vrf_name)
expected_vrf_status

2023-09-05 08:35 UTC, AbhijeetGSLAB commented on nrfu_tests/test_acls_api_access_list.py
> +                    f"Following Vrfs are not ACL configured:\n{vrf_configured_status}."
```suggestion
                    f"Following vrfs are not ACL configured:\n{vrf_configured_status}."
```

2023-09-05 08:37 UTC, AbhijeetGSLAB commented on nrfu_tests/test_acls_api_access_list.py
> +            # Forming output message if test result is failed.
![image](https://github.com/aristanetworks/vane/assets/94595571/640d58ec-d5aa-4e4a-9fad-3a5521cc7605)

Can we just add the vrf names that are not configured. As in the msg we are stating that its not configured and the same is added again below.

2023-09-05 08:41 UTC, AbhijeetGSLAB commented on nrfu_tests/test_acls_api_access_list.py
> +            collecting ACLs. Also, verifying VRFs are acl configured.
```suggestion
            TS: Running `show management api http-commands` and
            `show management api http-commands ip access-list summary` commands
            and verifying that all the VRFs are ACL configured.
```

2023-09-05 10:04 UTC, rohitsinghgslab commented on nrfu_tests/test_acls_api_access_list.py
> +                    actual_vrf_status = tops.actual_output["vrf_details"].get(vrf_name)
removed this, as in suggested failure msg it is not required.

2023-09-05 11:50 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_api_access_list.py
> +                    if not acl_found:
check this condition

2023-09-05 12:24 UTC, AbhijeetGSLAB approved these changes

2023-09-06 06:24 UTC, MaheshGSLAB requested changes

2023-09-06 06:24 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_api_access_list.py
> +            `show management api http-commands ip access-list summary` commands
separate out the TS for each show command

2023-09-06 06:24 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_api_access_list.py
> +                    f"Following vrfs are not ACL configured: {vrf_configured_status}."
Take the reference of PR 474 for TS/observation

2023-09-06 06:24 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_api_access_list.py
> +            output_api_acls = dut["output"][tops.show_cmds[tops.dut_name][1]]["json"]
dut output should match with observation. Dont use hardcode output
![image](https://github.com/aristanetworks/vane/assets/122076792/c2fe626e-771f-4f93-964d-df43fdd51186)

2023-09-06 06:24 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_api_access_list.py
> +                        tops.actual_output["vrf_details"].update({vrf: "Not Configured"})
Please update your actual and expected output. configured/not configured is giving proper details. Take the reference of PR 474
![image](https://github.com/aristanetworks/vane/assets/122076792/6213f7ae-9c84-464c-8548-282a8ad97bbb)

2023-09-06 06:24 UTC, MaheshGSLAB commented on nrfu_tests/test_security_rp_api_access_list.py
> +    test_duts = dut_parameters["test_acls_api_vrfs_enabled"]["duts"]
Why you are not running the testcase on BOFA lab?
![image](https://github.com/aristanetworks/vane/assets/122076792/fc892f07-3358-4a9d-b308-74dc54afbee0)

2023-09-08 10:02 UTC, MaheshGSLAB requested changes

2023-09-11 04:36 UTC, MaheshGSLAB approved these changes

2023-09-19 23:17 UTC, rewati-arista requested changes
Minor rephrasing suggestions, rest looks good

2023-09-19 23:17 UTC, rewati-arista commented on nrfu_tests/test_security_rp_api_access_list.py
> +        tops.output_msg = "All VRFs that the API is active on, an ACL is configured."
Can we rephrase this to "ACL is configured on all VRF's which have API enabled". Across the changed files the same sentence has been conveyed in many ways already, lets try and keep the phrasing simple and consistent 😅

2023-09-19 23:17 UTC, rewati-arista commented on nrfu_tests/test_security_rp_api_access_list.py
> +            assert api_acls, "ACL details for APIs is not found in the output."
```suggestion
            assert api_acls, "ACL details for APIs are not found in the output."
```

2023-09-19 23:17 UTC, rewati-arista commented on nrfu_tests/test_definition.yaml
> +      test_criteria: All VRFs that the API is active on should have an ACL to be configured. # Setting test case’s pass/fail criteria for reporting
lets keep phrasing consistent between description and criteria
```suggestion
      test_criteria: ACL should be configured on all VRFs on which API is enabled. # Setting test case’s pass/fail criteria for reporting
```

2023-09-19 23:17 UTC, rewati-arista commented on nrfu_tests/test_definition.yaml.j2
> +      test_criteria: All VRFs that the API is active on should have an ACL to be configured.
same suggestion as above

2023-09-20 07:01 UTC, rohitsinghgslab commented on nrfu_tests/test_definition.yaml.j2
> +      test_criteria: All VRFs that the API is active on should have an ACL to be configured.
Done

2023-09-20 07:12 UTC, rohitsinghgslab commented on nrfu_tests/test_security_rp_api_access_list.py
> +        tops.output_msg = "All VRFs that the API is active on, an ACL is configured."
True, changed it.

2023-09-20 07:12 UTC, rohitsinghgslab commented on nrfu_tests/test_definition.yaml
> +      test_criteria: All VRFs that the API is active on should have an ACL to be configured. # Setting test case’s pass/fail criteria for reporting
Done

2023-09-20 15:47 UTC, rewati-arista approved these changes
LGTM

2023-09-20 15:47 UTC, merged