Issue-419: Convert Pytest-CVP DNS test case to Vane
aristanetworks/vane pull request #513
Opened 2023-09-01 09:35 UTC by AbhijeetGSLAB

# Please include a summary of the changes

* test_definition.yaml: Updated test def with testcase NRFU1.1
* test_definition.yaml.j2: Updated J2 with testcase NRFU1.1
* nrfu_tests/nrfu_tests/test_base_services_dns.py: Added testcase for NRFU1.1
* masterdef.yaml: Updated master def file with global filter and testcase data

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link
#419 

Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (NRFU Testcase)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?
Unit Testing:

Note: Tested the IPv6 name servers using the IP for which DNS is configured by hardcoding the output

1. Tested the testcase for pass scenario where DNS is reachable:
    [report_2309011427.docx](https://github.com/aristanetworks/vane/files/12496505/report_2309011427.docx)
    [Pass HTML.zip](https://github.com/aristanetworks/vane/files/12496508/Pass.HTML.zip)

2. Tested the testcase for fail scenario where the DNS is not successful.
    [report_2309011431.docx](https://github.com/aristanetworks/vane/files/12496515/report_2309011431.docx)
    [Fail Reports.zip](https://github.com/aristanetworks/vane/files/12496521/Fail.Reports.zip)

3. Tested the testcase for pass scenario using J2 File.
    [dns_pass_with_J2.docx](https://github.com/aristanetworks/vane/files/12496534/dns_pass_with_J2.docx)
    [Pass using J2.zip](https://github.com/aristanetworks/vane/files/12496540/Pass.using.J2.zip)

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-09-04 11:08 UTC, hsisalgslab commented on nrfu_tests/test_base_services_dns.py
> +            TS: Running 'show ip name-server' command on the device and verifying the
```suggestion
            TS: Running `show ip name-server` command on the device and verifying the
```

2023-09-04 11:11 UTC, hsisalgslab commented on nrfu_tests/test_base_services_dns.py
> +            except pyeapi.eapilib.CommandError:
```suggestion
            except EapiError as error:
```
pls use this one

2023-09-04 11:14 UTC, hsisalgslab commented on nrfu_tests/test_definition.yaml.j2
> +    dns_name_server_check: # If you need it to fail if a name-server is not configured, change this to True for the IP version you need.
comments in J2 should above to line

2023-09-04 11:17 UTC, hsisalgslab commented on nrfu_tests/test_definition.yaml
> +      ipv4_fail_if_not_configured: True
```suggestion
      ipv4_is_not_configured: True
```

2023-09-04 11:20 UTC, hsisalgslab commented on nrfu_tests/test_definition.yaml
> +      ipv6_fail_if_not_configured: True
```suggestion
      ipv6_name_sever_is_configured: True
```

2023-09-04 11:28 UTC, hsisalgslab commented on nrfu_tests/test_definition.yaml.j2
> +    {% set test_data = master_data["NRFU1.1"] %}
test_data  is not used anywhere

2023-09-05 05:24 UTC, hsisalgslab approved these changes

2023-09-05 07:26 UTC, vishwajeetgslab requested changes

2023-09-05 07:26 UTC, vishwajeetgslab commented on nrfu_tests/test_dns_base_services.py
> +                )
```suggestion
            version_verification = [element for element in list(test_params.values())]
            if not all(version_verification):
                pytest.skip(
                    f"Name servers are not configured on {tops.dut_name}, hence skipping the"
                    " testcase."
                )
```

2023-09-05 07:26 UTC, vishwajeetgslab commented on nrfu_tests/test_dns_base_services.py
> +                    tops.actual_output.update({f"{ip_version}_dns_request_successful": True})
name_servers: ipv4: 8.8.8.8: reverse_nslookup_successful: True

2023-09-05 07:26 UTC, vishwajeetgslab commented on nrfu_tests/test_dns_base_services.py
> +                            f"DNS request is not successful for {ip_version} version.\n"
Reverse name server lookup failed for name servers {ip} configured on the device

2023-09-06 10:58 UTC, vishwajeetgslab requested changes

2023-09-06 10:58 UTC, vishwajeetgslab commented on nrfu_tests/test_dns_base_services.py
> +                            ip_version = ip_version_verification.split("_")[0]
Add this line above if condition so repeated lines can be removed.

2023-09-06 15:30 UTC, vishwajeetgslab approved these changes

2023-09-29 14:44 UTC, kgrozis-arista commented on nrfu_tests/test_dns_base_services.py
> +            if not any(version_verification):
How is it being verified on switch that name servers are not configured?

2023-10-03 07:19 UTC, AbhijeetGSLAB commented on nrfu_tests/test_dns_base_services.py
> +            if not any(version_verification):
Hi Kevin,
Depending upon the checks that are required to be verified in the test definition file and master def file, we are skipping the testcase. If both the checks in dns_name_server_check are set to false, the testcase will be skipped. We had a discussion on the same in the sync up call.
Thanks

2023-10-05 13:54 UTC, kgrozis-arista approved these changes

2023-10-05 13:54 UTC, merged