Make role field optional in duts.yaml
aristanetworks/vane pull request #539
Opened 2023-09-26 20:13 UTC by rewati-arista

# Please include a summary of the changes

* tests_tools.py -> add role to be None in case role is not present in duts.yaml, so now Vane does not fail if role field is not present in duts file
* test_tests_tools.py -> added tests to verify the above change
* fixture_duts_no_neighbors.yaml -> fixture added for testing wherein duts do not have role

# Include the Issue number and link

https://github.com/aristanetworks/vane/issues/463

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [X] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [ ] Other (please specify)

# Effort required on reviewers end

- - [X] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?
    
## New feature

Ensured current test cases pass and included newer test cases:

<img width="1391" alt="Screenshot 2023-09-26 at 1 13 23 PM" src="https://github.com/aristanetworks/vane/assets/123415500/805d6784-022b-4645-b7e1-20aabe0631a2">
    
# CI pipeline result

- - [X] Pass
- - [ ] Fail

2023-10-02 16:22 UTC, kgrozis-arista approved these changes

2024-04-10 20:15 UTC, grybak-arista requested changes
This looks good, but I think a small change might be more pythonic.

2024-04-10 20:15 UTC, grybak-arista commented on vane/tests_tools.py
>          login_ptr["role"] = dut["role"]
Rather than assigning value to the dut dictionary then reassigning to the login_ptr dictionary, maybe just use the dictionary.get() method with a default of an empty string.

```suggestion
        login_ptr["role"] = dut.get("role", "")
```

2024-04-10 20:38 UTC, rewati-arista commented on vane/tests_tools.py
>          login_ptr["role"] = dut["role"]
@grybak-arista thanks for the suggestion, should be good now?

2024-04-10 20:41 UTC, rewati-arista commented on vane/tests_tools.py
>          login_ptr["role"] = dut["role"]
Also @grybak-arista this PR is from when coverage and unittests were under same workflow "unittest" so after you resolve this conversation, you should be good to merge it (will have to bypass the workflow)👍🏻

2024-04-10 21:27 UTC, grybak-arista approved these changes
Looks great!

2024-04-10 21:27 UTC, grybak-arista commented on vane/tests_tools.py
>          login_ptr["role"] = dut["role"]
perfect!

2024-04-10 21:28 UTC, merged