issue-568: Updated testcase with ignore minidump directory
aristanetworks/vane pull request #578
Opened 2023-10-13 04:59 UTC by MaheshGSLAB

# Please include a summary of the changes

test_system_hardware_coredump.py: Updated the logic to ignore minidump directory. 

# Any specific logic/part of code you need extra attention on

NA

#568 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (Updated the code for arBGP enabled devices)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

## Bug fix

1. Testcase pass when there is no dump files:
[report_2310131018.docx](https://github.com/aristanetworks/vane/files/12889673/report_2310131018.docx), 
[report_2310131017.zip](https://github.com/aristanetworks/vane/files/12889678/report_2310131017.zip)

3. Testcase fails when there is dump file under /var/core: 
[report_2310131021.docx](https://github.com/aristanetworks/vane/files/12889683/report_2310131021.docx)
[report_2310131020.zip](https://github.com/aristanetworks/vane/files/12889684/report_2310131020.zip)

    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-10-13 13:40 UTC, kgrozis-arista requested changes

2023-10-13 13:40 UTC, kgrozis-arista commented on nrfu_tests/test_system_hardware_coredump.py
> +            if core_dump == ["minidump"]:
@MaheshGSLAB I don't see this logic as correct.  Minidump could be one of many files.  Current logic assumes minidump will be only file.

Need to test if minidump is an item in the core_dump list and if so remove it from the core_dump list.

2023-10-16 12:58 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_coredump.py
> +            if core_dump == ["minidump"]:
@kgrozis-arista 
Here if there are multiple files then value of core_dump will be like ["minidump", "sample.log", "test.log"] so our if condition will not satisfied in in that case testcase will fail which is expected. 

If there is no files in code dump then it will be two case:
1. If arBGP is not enabled: In that case IF condition will not satisfied and testcase will pass which is expected.
2. If arBGP is enabled then core dump will be ["minidump"] and here IF condition satisfied and we are going to empty the list and testcase pass which is expected.

As suggested we can go with your changes too. There also we first need to check if "minidump" in core dump files then remove it. So in that case also a IF condition will require. Let us know if we need to make the change.

2023-10-17 09:34 UTC, vishwajeetgslab approved these changes

2023-10-18 08:21 UTC, geetanjalimanegslab approved these changes
LGTM

2023-10-23 12:21 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_coredump.py
> +            if core_dump == ["minidump"]:
Updated the logic as suggested

2024-03-26 18:13 UTC, rewati-arista commented
Closing this PR since change replicated in https://github.com/aristanetworks/vane/commit/1de112af58199b1f67781731159fbd41282e653a

2024-03-26 18:13 UTC, closed without merging