Issue-567: Fixed the test_system_hardware_inventory supervisor behavior
aristanetworks/vane pull request #579
Opened 2023-10-13 11:19 UTC by AbhijeetGSLAB

# Please include a summary of the changes

nrfu_tests/test_system_hardware_inventory.py: Updated the testcase logic for skipping the testcase if card slots are not inserted.

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link
#567 

Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (Updated the code steps for skip scenario if the cards slots are not there on the device)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

## Bug fix

    1. Testcase pass if the CardSlots are not inserted.
        [report_2310131404.docx](https://github.com/aristanetworks/vane/files/12892791/report_2310131404.docx)
        [Pass Report card skip.zip](https://github.com/aristanetworks/vane/files/12892794/Pass.Report.card.skip.zip)

    2. Testcase fails if card slots are present but supervisor card is not inserted and linecard fail check if slot is missing is set to 
        True
         [report_2310131452.docx](https://github.com/aristanetworks/vane/files/12892802/report_2310131452.docx)
         [Supervisor Fail.zip](https://github.com/aristanetworks/vane/files/12892804/Supervisor.Fail.zip)

    3. Testcase fail when the linecard fail check is set to False.
        [Linecard Check.zip](https://github.com/aristanetworks/vane/files/12892842/Linecard.Check.zip)
        [report_2310131456.docx](https://github.com/aristanetworks/vane/files/12892844/report_2310131456.docx)

   4. Pass Report when everything is configured on the device.
       [Pass Inventory.zip](https://github.com/aristanetworks/vane/files/12892854/Pass.Inventory.zip)
       [report_2310131522.docx](https://github.com/aristanetworks/vane/files/12892855/report_2310131522.docx)
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-10-16 09:19 UTC, MaheshGSLAB requested changes

2023-10-17 04:39 UTC, MaheshGSLAB requested changes

2023-10-17 04:39 UTC, MaheshGSLAB commented on nrfu_tests/test_system_hardware_inventory.py
> +                tops.output_msg = (
i dont think this is correct skip. We added flag to fail or ignore the verification. If all flag are true that mean we have to first check that all type of cards are inserted if not then fail with correct reason. Until unless is task it is mention that if all flag are true then skip it

2023-10-17 08:29 UTC, vishwajeetgslab requested changes

2023-10-17 11:17 UTC, AbhijeetGSLAB commented on nrfu_tests/test_system_hardware_inventory.py
> +                tops.output_msg = (
As discussed, removed that particular skip as it is not necessary

2023-10-17 12:00 UTC, vishwajeetgslab approved these changes

2023-10-18 08:48 UTC, MaheshGSLAB approved these changes

2024-05-08 18:12 UTC, kgrozis-arista approved these changes

2024-05-08 18:13 UTC, kgrozis-arista commented
@vishwajeetgslab I've approved can you resolve conflicts

2024-06-26 13:29 UTC, merged