Updating skip functionality and fixing type error in NRFU4.3 test_routing_evpn_l2vni_imet testcase
aristanetworks/vane pull request #582
Opened 2023-10-16 12:20 UTC by vitthalmagadum

# Please include a summary of the changes
test_routing_evpn_l2vni_imet.py: Updating skip functionality and fixing type error in NRFU4.3

# Include the Issue number and link
https://github.com/aristanetworks/vane/issues/581

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [X] Other (NRFU Tests)

# Effort required on reviewers end

- - [X] Easy
- - [ ] Medium
- - [ ] Hard 

# Reports

Passed reports when EVPN routes are advertised for all VNIs
[report_passed.docx](https://github.com/aristanetworks/vane/files/12916232/report_passed.docx)

Failed reports when test criteria does not met( tested using hardcoded output)
[report_failed.docx](https://github.com/aristanetworks/vane/files/12916229/report_failed.docx)

Skipped reports when vxlan not configured.
[report_skipped_as_vxlan_interface_not_found.docx](https://github.com/aristanetworks/vane/files/12981686/report_skipped_as_vxlan_interface_not_found.docx)

Skipped reports when ribd model protocol is enabled. EVPN is not configured
[report_Skipped_when_device_is_in_ribd_mode.docx](https://github.com/aristanetworks/vane/files/12981680/report_Skipped_when_device_is_in_ribd_mode.docx)

HTML reports
[html_reports.zip](https://github.com/aristanetworks/vane/files/12981690/html_reports.zip)

2023-10-17 07:36 UTC, AbhijeetGSLAB approved these changes

2023-10-17 10:11 UTC, vishwajeetgslab requested changes

2023-10-17 10:11 UTC, vishwajeetgslab commented on nrfu_tests/test_routing_evpn_l2vni_imet.py
> +                    " exist / no L2 VNIs."
```suggestion
                    f"Skipping test case on {tops.dut_name} as interface {vxlan_interface} does not"
                    " exist / no L2 VNIs."
```

2023-10-18 05:20 UTC, vishwajeetgslab approved these changes

2023-10-18 07:28 UTC, MaheshGSLAB approved these changes

2024-03-26 18:08 UTC, rewati-arista approved these changes

2024-03-26 18:10 UTC, merged

2024-03-26 18:10 UTC, rewati-arista commented
Overrode the check since unittest pipeline has since been updated