Initial ixia logic, pending formatting and handling of port error
aristanetworks/vane pull request #590
Opened 2023-10-20 22:58 UTC by rewati-arista

# Please include a summary of the changes

* File 1 and corresponding changes
* File 2 and corresponding changes

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link

Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [ ] Other (please specify)

# Effort required on reviewers end

- - [ ] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2023-10-23 18:28 UTC, kgrozis-arista requested changes

2023-10-23 18:28 UTC, kgrozis-arista commented on sample_network_tests/ixia/tests/sample_ixia_duts.yaml
> +ixia:
new high-level for packet generators not called ixia
have a type field for packet generator

2023-10-24 18:28 UTC, rewati-arista commented on sample_network_tests/ixia/tests/sample_ixia_duts.yaml
> +ixia:
does this address it now: https://github.com/aristanetworks/vane/blob/6318f14dc025bdfb7d1b25de15ae56ff140be0b8/sample_network_tests/traffic_generator/tests/sample_traffic_generator_duts.yaml#L28

2023-10-26 14:24 UTC, shachiagarwal approved these changes

2023-10-26 16:58 UTC, rewati-arista commented on vane/tests_tools.py
> +        except Exception as exception:  # pylint: disable=W0718
So right now even if an error happened in Ixia, the Vane run happens successfully and the specific test case gets skipped and its test case log notifies the user that the test case got skipped due to an error while running ixia session. And the user can see the exact reason for exception in the vane.log file as well. Are you instead suggesting that we raise exception and basically have the test exit out with a failure citing an exception has occurred?

2023-10-26 17:15 UTC, rewati-arista commented on vane/tests_tools.py
> +        except Exception as exception:  # pylint: disable=W0718
I like the approach without raise exception because it does not confuse the user into believing that the failure was an actual test case failure but instead was an ixia session failure by showing that the test case was skipped due to an ixia error and also logging the specific ixia error. Its a bit cleaner I feel 😅. What do you think?

2023-10-26 17:22 UTC, shachiagarwal commented on vane/tests_tools.py
> +        except Exception as exception:  # pylint: disable=W0718
Now that you put it this way, I would like to ask @kgrozis-arista @grybak-arista about their views. My view still remains unchanged. I would like to see test case fail with exact ixia failure.

2023-10-26 17:48 UTC, rewati-arista commented on vane/tests_tools.py
> +    def setup_ixia(self, ixia_configuration):
addressed 0ea8b3a6ab560f57024862ec49b82b40c87e88ff :)

2023-10-26 18:41 UTC, shachiagarwal approved these changes

2023-10-27 16:53 UTC, grybak-arista approved these changes
Looks good! I left my thoughts on the discussion of the exception when Ixia setup fails, but approving the PR.

2023-10-27 16:53 UTC, grybak-arista commented on vane/tests_tools.py
> +        except Exception as exception:  # pylint: disable=W0718
I think I might agree with @shachiagarwal here, that the ixia, or the traffic generator, configuration and setup itself is part of the test case, and a failure there is a failure in the test case. 

The sample test case you have is to test "basic ixia setup" which I think would mean if the ixia session can't be started, then something is possibly wrong with the ixia configuration that we passed into the test. Yes, the problem could be outside the test configuration, but I think that those cases would probably be less likely than a misconfiguration of the traffic gen params.

Just my thoughts, though.

2023-10-31 18:39 UTC, merged