Added Generate test catalog functionality
aristanetworks/vane pull request #646
Opened 2024-02-12 12:53 UTC by vishwajeetgslab

# Please include a summary of the changes

* File 1 and corresponding changes
* File 2 and corresponding changes

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link

Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [ ] Other (please specify)

# Effort required on reviewers end

- - [ ] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2024-02-20 09:50 UTC, geetanjalimanegslab approved these changes

2024-02-20 23:46 UTC, rewati-arista requested changes
Thank you for getting this PR in, seems like a lot of work 🙌🏻 I have gone through and left my comments, please feel free to reach out for any clarifications, we can discuss through any differing opinions :) Lastly the validate tool (pylint specifically) is failing on a couple of files so kindly fix that before we get the PR in, once again thank you for the effort ⭐️

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +def test_walk_dir(logdebug, mocker):
we need a unit test case when more than one TEST DIR is passed

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +        logdebug.assert_any_call(debug_msg)
we dont need the for loop here
```suggestion
       logdebug.assert_has_calls(logdebug_calls, any_order=False)
```

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +        call("Parsing python and test definations.yaml file for preparing test catalog."),
```suggestion
        call("Parsing python and test definitions.yaml file for preparing test catalog."),
```

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +        for log in files:
```suggestion
        for file in files:
```

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +def test_parsed_data(loginfo, logdebug, mocker):
logic to test the setting of values in self.test_def_data within the try block needs to be added, to ensure reading and assigning of yaml data is happening correctly

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +
unit tests for get_parsed_data_from_python_file and get_correlated_data have not been added

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +    final_data = {
lets add this as a fixture and use the read_yaml utility to read it into final_data

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +    final_data = {
use the same fixture as mentioned above

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +    mocker.patch("vane.test_catalog_client.return_date", return_value=("not_used", "2402182049"))
ideally we should also be patching get_data_rows since this is a unit test for write_to_csv

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +    path = request.config.rootpath
ah this is smart :) I wish I had known about this when I wrote my unittests :))

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +    # Added mocker for retrun date function.
```suggestion
    # Added mocker for return date function.
```

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +        # Removing the CSV file created. if not deleted already.
nitpick, sorry 😅
```suggestion
        # Removing the CSV file created, if not deleted already.
```

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +        actual_data = []
for consistency
```suggestion
        actual_rows = []
```

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +                actual_data.append(row)
```suggestion
                actual_rows.append(row)
```

2024-02-20 23:46 UTC, rewati-arista commented on tests/unittests/test_tests_catalog.py
> +    assert actual_data == expected_rows
```suggestion
    assert actual_rows == expected_rows
```

2024-02-21 00:01 UTC, rewati-arista commented
Adding the comments here since these are not directly code related:

(1) I think the manual test cases described in the PR info are very helpful and cover the functionality well, is there a reason why we could not include them in our python test cases?

(2) Do not worry about the pip-install check failing in pipeline, there is an issue to address the same, however kindly take care of the validate pipeline failing due to pylint.

2024-03-05 17:36 UTC, vishwajeetgslab commented
Hi @rewati-arista, I have now addressed all the review comments on MR. Can you please review it once.

2024-03-07 22:46 UTC, rewati-arista commented
> Adding the comments here since these are not directly code related:
> 
> (1) I think the manual test cases described in the PR info are very helpful and cover the functionality well, is there a reason why we could not include them in our python test cases?
> 
For this can we still keep the description of manual test cases in the PR info for reference?

2024-03-07 22:50 UTC, rewati-arista requested changes
Thank you for addressing the past comments. I was not able to see a few comments addressed, my apologies if I missed those, kindly point them out to me if I did or make the changes as needed. A few other minor suggestions and I think we should be good once we address those. Once again let me know if you need further clarifications 👍🏻

2024-03-07 22:50 UTC, rewati-arista commented on tests/unittests/fixtures/test_catalog_client/no_tests_in_file.csv
> +Test Suite,Test Case ID,Test Case,Description,Test Steps
naming got me a bit confused, "no_tests_in_file", what is this fixture exactly helping with? or is it supposed to be no_tests_in_python_file.csv? (assuming by the .py file next)

2024-03-07 22:50 UTC, rewati-arista commented on tests/unittests/fixtures/test_catalog_client/no_test_steps_in_python_file/test_definition.yaml
> +- name: api_tests
when i run the unittests, for each of these test_definition.yaml, a test_definition_regenerated.yaml gets created within the fixtures locally, can we provide to clean that up?

2024-03-07 22:50 UTC, rewati-arista commented on tests/unittests/fixtures/test_catalog_client/parsed_test_def.json
> +{
I could not find this file being referenced anywhere in unittests, should we delete it?

2024-03-11 05:06 UTC, vishwajeetgslab commented on pytest.ini
> +# execulde directories
Hi Rewati, As discussed over the chat. Keeping it as `exclude directories`

2024-03-11 05:08 UTC, vishwajeetgslab commented on vane/test_catalog_client.py
> +            if not old_test_file:
Yes, moving the test_suite name outside loop works. initially i was passing all files at once hence added that check. Now i have removed it outside the loop.

2024-03-11 05:08 UTC, vishwajeetgslab commented on tests/unittests/fixtures/test_catalog_client/no_test_steps_in_python_file/test_definition.yaml
> +- name: api_tests
Hi Rewati, found this test case(https://github.com/aristanetworks/vane/blob/b365caafa1bdf45c44121c5bf79b248e98a43707/tests/unittests/test_tests_client.py#L89) having an recursive call to directories and it causing the test_definition_regenerated.yaml files gets created for all directories inside fixtures. https://github.com/aristanetworks/vane/blob/b365caafa1bdf45c44121c5bf79b248e98a43707/vane/tests_client.py#L99

2024-03-11 08:55 UTC, vishwajeetgslab commented on tests/unittests/test_tests_catalog.py
> +
Updated.

2024-03-11 08:56 UTC, vishwajeetgslab commented on tests/unittests/test_tests_catalog.py
> +    mocker.patch("vane.test_catalog_client.return_date", return_value=("not_used", "2402182049"))
updated

2024-03-11 08:56 UTC, vishwajeetgslab commented on tests/unittests/test_test_catalog_client.py
> +def test_correlate_test_data(mocker, loginfo):
updated as per suggestion

2024-03-11 08:56 UTC, vishwajeetgslab commented on vane/test_catalog_client.py
> +        file_name = f"test_catalog_{file_date}.csv"
Added file timestamp in seconds now

2024-03-11 08:57 UTC, vishwajeetgslab commented on tests/unittests/fixtures/test_catalog_client/no_tests_in_file.csv
> +Test Suite,Test Case ID,Test Case,Description,Test Steps
updated file name as no_tests_in_python_file.csv

2024-03-11 08:59 UTC, vishwajeetgslab commented on tests/unittests/fixtures/test_catalog_client/parsed_test_def.json
> +{
Now this file is used in test_parse_test_data unit test case.

2024-03-11 08:59 UTC, vishwajeetgslab commented on vane/test_catalog_client.py
> +                                                    "Test ID is not found in the"
updated.

2024-03-11 09:26 UTC, vishwajeetgslab commented on tests/unittests/test_tests_catalog.py
> +def test_parsed_data(loginfo, logdebug, mocker):
updated.

2024-03-11 14:02 UTC, rewati-arista commented on tests/unittests/fixtures/test_catalog_client/no_test_steps_in_python_file/test_definition.yaml
> +- name: api_tests
Created https://github.com/aristanetworks/vane/issues/661 to handle this

2024-03-11 14:32 UTC, rewati-arista approved these changes
LGTM, thank you for addressing all comments. I will make the documentation update on my end and we should be good to merge after that 👍🏻

2024-03-11 14:56 UTC, rewati-arista commented on vane/vane_cli.py
> +from vane import test_catalog_client
https://github.com/aristanetworks/vane/pull/609/commits/98cfa74f86c06d940fa1e3461972c8d37f359738

Updated docs

2024-03-12 06:35 UTC, shachiagarwal commented on vane/test_catalog_client.py
> +                    or name == "test_definition.yaml"
Can we change "test_definition.yaml" is incorrect here. Name of the file should be picked from definitions["test_definitions"].

2024-03-12 06:38 UTC, shachiagarwal commented on vane/test_catalog_client.py
> +        final_data = copy.deepcopy(self.test_def_data)
Why do we need a deepcopy here?

2024-03-12 06:46 UTC, shachiagarwal commented on vane/test_catalog_client.py
> +    def write_to_csv(self, final_data):
Should have made this a utility func. No need for this to be part of the class.

2024-03-28 16:05 UTC, vishwajeetgslab commented on vane/test_catalog_client.py
> +        final_data = copy.deepcopy(self.test_def_data)
Removed deepcopy used in the code.

2024-03-28 20:47 UTC, rewati-arista approved these changes
LGTM

2024-03-28 20:47 UTC, rewati-arista commented on tests/unittests/fixtures/test_catalog_client/pass_dirs/non_default_test_def/test_api.py
It is fine for now, but next time when we add files for fixture purposes lets try and add files which are shorter in content since the content does not really matter. Keeps the code shorter and avoids unnecessary bloat.

2024-04-15 15:50 UTC, kgrozis-arista approved these changes

2024-04-15 15:50 UTC, merged