issue_62: NRFU6.10: Update skip enhancement
aristanetworks/vane pull request #681
Opened 2024-03-15 09:15 UTC by rahulmali2512

# Please include a summary of the changes

* Updated test_hardware_power_supply_voltage_status.py with NRFU6.10 testcase changes

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link

Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [x] Other (please specify)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

- Skipped reports when device is vEOS device.

[report_2403151146.docx](https://github.com/aristanetworks/vane/files/14613315/report_2403151146.docx)

- HTML reports

[skip.zip](https://github.com/aristanetworks/vane/files/14613323/skip.zip)

2024-03-20 03:33 UTC, dhruvgoel9 commented on nrfu_tests/test_hardware_power_supply_voltage_status.py
> +        except (BaseException, EapiError) as excep:
Revert the changes of except block, don't add pytest skip exception

2024-03-20 03:34 UTC, dhruvgoel9 commented on nrfu_tests/test_hardware_power_supply_voltage_status.py
> +            for voltage_sensor in self.power_voltage_sensor:
Why these changes are required

2024-03-20 03:37 UTC, dhruvgoel9 reviewed
Update the task accordingly

2024-03-22 09:18 UTC, dhruvgoel9 commented on nrfu_tests/test_hardware_power_supply_voltage_status.py
> +                f"\nOutput of {power_supply_cmd} command is:\n{voltage_cmd_output}\n"
Why we have made these changes

2024-03-22 09:48 UTC, dhruvgoel9 approved these changes

2024-03-22 10:45 UTC, geetanjalimanegslab approved these changes

2024-03-22 20:57 UTC, rewati-arista commented on nrfu_tests/test_hardware_power_supply_voltage_status.py
>              if "vEOS" in version_output.get("modelName"):
Why are we not using model here?
```suggestion
            if "vEOS" in model:
```

2024-03-22 20:58 UTC, rewati-arista requested changes
One change requested about variable usage

2024-03-25 15:15 UTC, rewati-arista approved these changes

2024-03-26 19:10 UTC, merged