Added module to remove empty log files
aristanetworks/vane pull request #732
Opened 2024-03-28 00:37 UTC by rewati-arista

# Please include a summary of the changes

* File 1 and corresponding changes
* File 2 and corresponding changes

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link

Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [ ] Other (please specify)

# Effort required on reviewers end

- - [ ] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2024-04-03 12:52 UTC, kgrozis-arista approved these changes

2024-04-03 12:54 UTC, kgrozis-arista commented
FYI - @rewati-arista pip install pipeline has failed

2024-04-03 14:06 UTC, rewati-arista commented
> FYI - @rewati-arista pip install pipeline has failed

yeah its because it has the old cli flags it is checking for, should be good in reality since the fix to pip install has been pushed since then

2024-04-11 18:09 UTC, grybak-arista requested changes
This looks good, except for one small request.

2024-04-11 18:09 UTC, grybak-arista commented on vane/vane_cli.py
> +                os.remove(file_path)
I think there should be some error handling here, just in case. Since we are not checking doing an extensive check on the files that are in the logs directory before deleting, what if the logs directory pre-existed and I had created a file in there that the vane execution could not delete? If the `os.remove()` fails for any reason, we need to catch it. I think ignoring the file and maybe logging the error (or ignoring it as well) would be fine. This most likely would not happen, but you never know. 🤷🏻 

Maybe there should be a warning somewhere in the docs (if it's not already there) that the log directory will be cleaned of any files that do not match test cases that were executed.

Just some thoughts.

2024-04-11 18:48 UTC, rewati-arista commented on vane/vane_cli.py
> +                os.remove(file_path)
Hey @grybak-arista you bring up a good point

If you look at this
https://github.com/aristanetworks/vane/blob/59f00eb84450687fa94d3cd8447cbb6cab30db95/vane/tests_client.py#L414
we clean the logs directory before the Vane run, we only allow vane.log file to remain. So that should address the first point of there technically never being any additional files we would overlook. Does that make sense?

The second point about warning about logs directory being cleaned every run, have added it here through this PR https://github.com/aristanetworks/vane/pull/747
<img width="782" alt="Screenshot 2024-04-11 at 11 43 20 AM" src="https://github.com/aristanetworks/vane/assets/123415500/9a762d25-02d5-496f-8737-c974b2d61683">


once you are good with this comment and that PR, feel free to approve and merge that PR as well since I think its fine to just have a +1 on a change of that nature (will avoid adding on to our PR list)

2024-04-11 20:17 UTC, grybak-arista commented on vane/vane_cli.py
> +                os.remove(file_path)
Thanks for the explanations @rewati-arista 

I will review the documentation PR - it looks good.

I still think the first issue needs a little attention - but maybe the error check needs to be placed in the `_remove_test_case_logs` function you mentioned. Here's an example where I added a locked file in the logs directory and then tried to run vane:
```
(vane-cvp-shell) 10-18-136-178 vane-data # vane --nrfu
Please input Arista device username: cvpadmin
Please input Arista device password:
Using CVP to gather duts data
Do you want to specify a custom test case directory [y|n]:n
Starting Execution of tests via Vane
Traceback (most recent call last):
  File "/home/cvp/.cache/pypoetry/virtualenvs/vane-6gE1vKXj-py3.9/bin/vane", line 6, in <module>
    sys.exit(main())
  File "/project/vane/vane_cli.py", line 296, in main
    run_tests(vane.config.DEFINITIONS_FILE, vane.config.DUTS_FILE)
  File "/project/vane/vane_cli.py", line 155, in run_tests
    vane_tests_client.setup_test_runner()
  File "/project/vane/tests_client.py", line 157, in setup_test_runner
    self._remove_test_case_logs()
  File "/project/vane/tests_client.py", line 415, in _remove_test_case_logs
    os.remove(file_path)
PermissionError: [Errno 1] Operation not permitted: 'logs/locked-file'
```
I think in this case we should ignore the file that couldn't be removed, or if others think we should error out and report that there is a rogue file in the logs directory we could do that as well.

Once again, something like this is probably very unlikely to happen, but it *could* happen, so it's best to handle it I think.

2024-04-11 22:24 UTC, rewati-arista commented on vane/vane_cli.py
> +                os.remove(file_path)
https://github.com/aristanetworks/vane/pull/732/commits/748559dc614c0bfec17d63560e19bead3bba68c5

2024-04-11 22:56 UTC, grybak-arista commented on vane/vane_cli.py
> +                os.remove(file_path)
Nice!

2024-04-11 22:56 UTC, grybak-arista approved these changes
This looks good! 👍🏻

2024-04-11 22:57 UTC, merged