Issue #658: Add support for only generating summary docx reports
aristanetworks/vane pull request #746
Opened 2024-04-05 23:54 UTC by shachiagarwal

# Please include a summary of the changes

* nrfu_client.py - ask whether user wants detailed report
* report_client.py - depending on `generate_only_summary_report` in definitions.yml - generate only summary docx reports

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link
closes #658 
Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [x] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [ ] Other (please specify)

# Effort required on reviewers end

- - [x] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [x] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2024-04-08 15:27 UTC, rewati-arista requested changes
A couple of minor nitpicks but we should address the other points: 
(1) Input validation
(2) Default value for certification testing

Thank you 😄

2024-04-08 15:27 UTC, rewati-arista commented on vane/nrfu_client.py
> +        user_choice = input(
Should we not have input validation similar to:
https://github.com/aristanetworks/vane/blob/2e1379c776be66f1e0c4a20a9b7b61dabb25ada5/vane/nrfu_client.py#L158

2024-04-08 15:27 UTC, rewati-arista commented on vane/nrfu_client.py
> +            "Do you want detailed report?(Press enter for Default: no) [y/yes/n/no]:"
nit pick:
```suggestion
            "Do you want detailed report?(Press Enter for the default option: "No") [y/yes/n/no]:"
```

2024-04-08 15:27 UTC, rewati-arista commented on vane/nrfu_client.py
> +        self._report_detail_level = True  # default only summary report
nitpick:
```suggestion
        self._report_detail_level = True  # default set to generate only summary report
```

2024-04-08 15:27 UTC, rewati-arista commented on vane/nrfu_client.py
> +        self._report_detail_level = True  # only summary report by default
nitpick:
```suggestion
        self._report_detail_level = True  # generate only summary report by default
```

2024-04-08 15:27 UTC, rewati-arista commented on vane/report_client.py
> +            "generate_only_summary_report", True
did we not want default for certification testing to be False?

2024-04-08 15:27 UTC, rewati-arista commented on tests/unittests/test_nrfu_client.py
> +    outputs = [True, False, False, True, True, True]
I dont think garbage should be considered as true😅 I think we should do input validation and only allow for legitimate values

2024-04-08 15:32 UTC, shachiagarwal commented on vane/nrfu_client.py
> +        user_choice = input(
Cant be. Pressing enter is also a valid choice.

2024-04-08 15:34 UTC, rewati-arista commented on vane/nrfu_client.py
> +        user_choice = input(
So we can add "" in this list of valid choices? I am assuming Enter gets read in as empty string right?

2024-04-08 17:05 UTC, shachiagarwal commented on tests/unittests/test_nrfu_client.py
> +    outputs = [True, False, False, True, True, True]
I think it should. I honestly dislike when a script keeps asking same question again and again. But I am open to Kevin's and Gary's perspective on this. To support my implementation, its not going to be end of world if one did not select right option here. Going by our reporting enhancements, user should be able to generate a detailed report without rerunning the tests.

2024-04-08 17:06 UTC, shachiagarwal commented on vane/report_client.py
> +            "generate_only_summary_report", True
Nope. I thought about this. To reduce vane run time this should default to summary only. Report generation can be run at a later point without rerunning the tests (as per reporting enhancements).

2024-04-16 17:26 UTC, shachiagarwal commented on vane/nrfu_client.py
> +        user_choice = input(
Then why should 'while' be used?

2024-04-16 17:39 UTC, rewati-arista commented on vane/nrfu_client.py
> +        user_choice = input(
so that until they either put in a "yes", "y", "no", "n", ""(enter) they get prompted again? basically we do not allow for garbage values as I mentioned in https://github.com/aristanetworks/vane/pull/746#discussion_r1556035822. If we decide to assume garbage value as "no" then we would not need this while, so this depends on the choice we make for that question.

2024-04-16 19:34 UTC, grybak-arista commented on vane/nrfu_client.py
> +        user_choice = input(
As an option, there is a python library called [PyInputPlus](https://pypi.org/project/PyInputPlus/) that handles input like this. Doing something like the following allows for handling mistyped responses and exits after a number of errors. Here I entered an empty reponse (<enter>), "maybe", and "wait", and the library assigned the result to the default of "no" after that.

```
>>> result = pyip.inputYesNo(prompt="\nDo you want detailed report?\n(3 invalid responses will assume the default response of \"no\") [y/yes/n/no]: ", limit=3, default="no")

Do you want detailed report?
(3 invalid responses will assume the default response of "no") [y/yes/n/no]: Blank values are not allowed.

Do you want detailed report?
(3 invalid responses will assume the default response of "no") [y/yes/n/no]: maybe
'maybe' is not a valid yes/no response.

Do you want detailed report?
(3 invalid responses will assume the default response of "no") [y/yes/n/no]: wait
'wait' is not a valid yes/no response.

>>> result
'no'
```

And here I reply "y" and the library applies the result "yes", the same would apply for "n" ("no" would be the result).

```
>>> result = pyip.inputYesNo(prompt="\nDo you want detailed report?\n(3 invalid responses will assume the default response of \"no\") [y/yes/n/no]: ", limit=3, default="no")

Do you want detailed report?
(3 invalid responses will assume the default response of "no") [y/yes/n/no]: y

>>> result
'yes'
```

Just another possible solution.

2024-04-16 19:50 UTC, grybak-arista requested changes
This looks good! Just a few requests and possible changes, then it should be good to go.

2024-04-16 19:50 UTC, grybak-arista commented on tests/unittests/fixtures/definitions_nrfu_custom_expected.yaml
> +  generate_only_summary_report: true
Maybe move `generate_only_summary_report` to the top of the parameter list to keep the list sorted? Everything else is already sorted.

2024-04-16 19:50 UTC, grybak-arista commented on tests/unittests/fixtures/definitions_nrfu_default_expected.yaml
> +  generate_only_summary_report: true
As in the other definitions file, maybe move generate_only_summary_report to the top of the parameter list to keep the list sorted?

2024-04-16 19:50 UTC, grybak-arista commented on vane/nrfu_client.py
> +            self._report_detail_level = False  # summary + detailed report
This seems a little confusing - if I answer "yes" to detailed report, then set `_report_detail_level` to False? Seems counterintuitive. I understand the logic, but at first reading it seemed to not make sense.

A suggestion would be to rename `self._report_detail_level` to `self._detailed_report` and swap the true/false values - i.e. true if detailed report is desired, false if only summary report is desired. Then later in line 310, set `generate_only_summary_report` to `not self._detailed_report`.

2024-04-16 19:50 UTC, grybak-arista commented on vane/nrfu_client.py
> +            "Do you want detailed report?(Press Enter for the default option: "No") [y/yes/n/no]:"
Minor changes to prompt phrasing and spacing:
```suggestion
            "Do you want a detailed report? (Press Enter for the default option: "No") [y/yes/n/no]: "
```

2024-04-16 20:09 UTC, rewati-arista commented on vane/nrfu_client.py
> +            self._report_detail_level = False  # summary + detailed report
I like this suggestion, well put Gary 🙌🏻

2024-04-17 23:18 UTC, shachiagarwal commented on tests/unittests/fixtures/definitions_nrfu_custom_expected.yaml
> +  generate_only_summary_report: true
Done

2024-04-17 23:18 UTC, shachiagarwal commented on tests/unittests/fixtures/definitions_nrfu_default_expected.yaml
> +  generate_only_summary_report: true
Done

2024-04-17 23:18 UTC, shachiagarwal commented on tests/unittests/test_nrfu_client.py
> +    outputs = [True, False, False, True, True, True]
I think I have tried to resolve this. Let me know what you think @rewati-arista

2024-04-17 23:18 UTC, shachiagarwal commented on vane/nrfu_client.py
> +        user_choice = input(
@grybak-arista I have not used your suggestion. Still I have tried to solve this problem. Let me know what you think. 
@rewati-arista Let me know what you think.

2024-04-17 23:18 UTC, shachiagarwal commented on vane/nrfu_client.py
> +            self._report_detail_level = False  # summary + detailed report
I have tried to stream line the variables and what they mean. Let me know what you think @grybak-arista @rewati-arista

2024-04-18 16:59 UTC, rewati-arista approved these changes
this seems fair to me 👍🏻 in future we should ensure consistency in how we handle user inputs in terms of validation (either enforce a default OR keep re-prompting till we get a valid response, either is fine imo, right now we are doing both, we should stick to one) its only a minor point to consider in future, so approving the PR

2024-04-18 17:00 UTC, rewati-arista commented on vane/nrfu_client.py
> +            self._report_detail_level = False  # summary + detailed report
good on my end, will let Gary resolve it once he approves :)

2024-04-18 17:01 UTC, rewati-arista commented on vane/nrfu_client.py
> +        user_choice = input(
good on my end, will let Gary resolve it once he approves :)

2024-04-18 22:26 UTC, grybak-arista commented on vane/nrfu_client.py
> +        user_choice = input(
Yes, I think this works

2024-04-18 22:27 UTC, grybak-arista commented on vane/nrfu_client.py
> +            self._report_detail_level = False  # summary + detailed report
This is much better! Awesome!

2024-04-18 22:28 UTC, grybak-arista approved these changes
This looks really good now!
👍🏻

2024-04-18 22:29 UTC, merged