Add an API to support evidence recording for commands executed via non-eAPI or non-netmiko connections
aristanetworks/vane pull request #749
Opened 2024-04-15 14:22 UTC by vishwajeetgslab

Add an API to support evidence recording for commands executed via non-eAPI or non-netmiko connections

# Please include a summary of the changes

* File 1 and corresponding changes
* File 2 and corresponding changes

# Any specific logic/part of code you need extra attention on

Explain any specific logic you need special attention on

# Include the Issue number and link

Make sure to link the issue in the github PR UI 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [ ] Other (please specify)

# Effort required on reviewers end

- - [ ] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Verify Documentation Update

    If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
    
# Additional comments

2024-04-30 10:24 UTC, geetanjalimanegslab approved these changes
LGTM

2024-04-30 19:07 UTC, rewati-arista requested changes
LGTM, minor suggestions and a few points we can discuss. Let me know if you need any clarifications on my end. Thank you 😄

2024-04-30 19:07 UTC, rewati-arista commented on tests/unittests/test_tests_tools.py
> +    assert show_output in captured_output.out
about the point @vishwajeetgslab you mentioned about testing for docx, in my opinion it is fine to not have that as of now since we do not have the infrastructure to test our docx as of now. I looked through the docx report and it looks good to me, one small suggestion would be if we could highlight the heading EXTERNAL DEVICE OUTPUT like this:
 
<img width="716" alt="Screenshot 2024-04-30 at 12 05 51 PM" src="https://github.com/aristanetworks/vane/assets/123415500/e812cb13-1eb3-457d-af55-64eaef49a2af">

2024-05-03 15:29 UTC, vishwajeetgslab commented on vane/tests_tools.py
> +                index = 1
Hi Rewati, as discussed Updated numbering with above format for both eos and non-eos devices. Thanks

2024-05-03 15:29 UTC, vishwajeetgslab commented on tests/unittests/test_tests_tools.py
> +    assert show_output in captured_output.out
As discussed on chat, Keeping as it is.

2024-05-03 15:38 UTC, vishwajeetgslab commented on vane/tests_tools.py
> +            prompt (str): It indicates where the command was executed other than the EOS device.
updated it as device_name.

2024-05-03 18:15 UTC, rewati-arista commented on vane/tests_tools.py
> +        # Checking whether the provided device is EOS device.
can this check not be evaluated against just self.dut_name (i.e: why do we check against all test duts), is there a possibility that this API gets called on an eos device that is not the exact device under test? as in not the dut the test object is initialized for?

2024-05-03 18:15 UTC, rewati-arista commented on vane/tests_tools.py
> +    def add_cmds_evidence(self, cmds, cmds_output, dut="", prompt=""):
https://github.com/aristanetworks/vane/pull/749/commits/ff7150d07e6efe6910b9a7c20213ed722f0f7062#r1589574749

2024-05-06 02:41 UTC, vishwajeetgslab commented on vane/tests_tools.py
> +        # Checking whether the provided device is EOS device.
Hi Rewati, In some cases we need to run commands on neighboring eos devices as well in the test case(Example: From one eos device we are running a ping traffic and on other eos device collecting the tcpdump output). so if we just use self.dut_name in that case we will not be able to distinguish between eos and non-eos device hence vane.config.test_duts is used here.

2024-05-06 17:20 UTC, rewati-arista approved these changes

2024-05-06 20:22 UTC, kgrozis-arista approved these changes

2024-05-06 20:22 UTC, kgrozis-arista commented
@vishwajeetgslab I approved changes.  Can you resolve conflicts?

2024-05-07 07:54 UTC, vishwajeetgslab commented
> @vishwajeetgslab I approved changes. Can you resolve conflicts?
Hi @kgrozis-arista , Resolved conflicts on MR. Thanks

2024-05-20 16:51 UTC, shachiagarwal approved these changes

2024-05-20 16:51 UTC, merged