issue_760: Test Feature request for Vane NRFU Test 6.11 - Fine tuning for DCS-7010* and CCS-710P* platforms
aristanetworks/vane pull request #761
Opened 2024-05-27 18:04 UTC by rohitsinghgslab

Description:Test Feature request for Vane NRFU Test 6.11 - Fine tuning for DCS-7010* and CCS-710P* platforms.

# Please include a summary of the changes

* test_system_hardware_temperature.py: Added enhancement changes in testcase NRFU6.11

# Any specific logic/part of code you need extra attention on

Fine tuning for DCS-7010* and CCS-710P*

# Include the Issue number and link
#760 

# List/Attach any dependencies/past issues that are required for this change/provide context

# Type of change

- - [ ] Bug fix (non-breaking change which fixes an issue)
- - [ ] New feature (non-breaking change which adds functionality)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - [ ] This change requires a documentation update
- - [ ] Other (please specify)

# Effort required on reviewers end

- - [ ] Easy
- - [ ] Medium
- - [ ] Hard 

# How Has This Been Tested?
Tested on Hardcoded output.

## Bug fix

    Include before and after snapshots/screenshots/changed logs
    
## New feature

    Ensure current test cases pass and include newer test cases if required
    
# CI pipeline result

- - [ ] Pass
- - [ ] Fail
  
  If it fails, explain the reason and whether or not we should ignore the failure
  
# Additional comments

*Gitlab link:- https://gitlab-gslab.act.arista.com/gslab-dev/pytest-cvp/-/issues/71

2024-05-29 02:37 UTC, AbhijeetGSLAB approved these changes

2024-05-30 12:25 UTC, vishwajeetgslab requested changes

2024-05-30 12:25 UTC, vishwajeetgslab commented on nrfu_tests/test_system_hardware_temperature.py
> +            system status and temperature sensors details are present in the output.
No need to update the TS here.

2024-06-03 05:10 UTC, vishwajeetgslab approved these changes

2024-06-26 13:20 UTC, kgrozis-arista approved these changes
LGTM

2024-06-26 13:20 UTC, merged